### ISSUE TITLE
Backporting dataset tools to coffea 0.7

### ISSUE THREAD

**Issue by ikrommyd** [scikit-hep/coffea#1034]
I think it would be a good idea to backport the dataset querying tools to coffea 0.7.
I believe we can just keep the rucio-utils as is and from the data discovery cli, removing just the preprocessing part which is tied to coffea 202x should do it.
I just think it would be nice to be able to query for datasets in the cases where coffea 0.7 is still in use (and those are a lot of cases apparently).

I can take it of course if you think it's a good thing to do. 

cc @lgray

**Comment by lgray** [comment]
Yep please go ahead.
