### ISSUE TITLE
Pass args to the dask `Client` from the dataset discovery cli

### ISSUE THREAD

**Issue by ikrommyd** [scikit-hep/coffea#1046]
Yesterday, @mmarchegiani found that the PSI cluster doesn't let you use `processes=True` which is the default when spawning up a local `Client`.
That is fine if you use the dataset tools from a script/notebook cause you can create your own `LocalCluster` or any other cluster and provide the scheduler url in the `do_preprocess` method but it's not an option when the dataset tools are used from the command line.
You can spawn a client from python elsewhere but that kinda defeats the purpose of the cli.
It would be nice to be able to provide args for the Client creation in the cli or at least just a bool processes argument.

**Comment by lgray** [comment]
https://github.com/CoffeaTeam/coffea/blob/master/src/coffea/dataset_tools/dataset_query.py#L653 doesn't work correctly?

You'd have to start the scheduler / cluster in another process, of course.

**Comment by lgray** [comment]
Otherwise covering all possible cases of how you want to generate a dask cluster is significantly out of scope for a CLI. It will result in an obtuse interface with too many options. 

i.e. it's of such complexity you should probably just write a script for it or a script for spawning the cluster you want, which would be more concise as a set of instructions.

**Comment by ikrommyd** [comment]
Yes passing in the `scheduler_url` works but as you said you have to start it in another process. Would it make sense then to  just have one more option to not use a `Client` and just use local `threads` for the cli?

**Comment by lgray** [comment]
Using threads would be *bad* since uproot is gil-heavy. You will not get any parallelism out of it.

Why does the PSI cluster not allow spawning of subprocesses? That seems rather daft in this day and age.

**Comment by ikrommyd** [comment]
That I don't know. @mmarchegiani will have to comment. I think there was also a solution with the multiprocessing module to  just block processes that way.

**Comment by ikrommyd** [comment]
@lgray Do you want to close this?

**Comment by mmarchegiani** [comment]
In the end I solved in my specific case by adding a call to `freeze_support()` in the main:
```
from multiprocessing import freeze_support

if __name__ == '__main__':
    freeze_support()

    parser = argparse.ArgumentParser(description='Create json dataset via CLI')
    parser.add_argument('-j', '--workers', default=8, type=int, help='Number of workers')
    args = parser.parse_args()

    # Start LocalCluster
    cluster = LocalCluster(
        n_workers=1,
        memory_limit="4GiB",
        processes=True,
        threads_per_worker=1
    )

    cluster.scale(args.workers)

    # Start dask client
    client = Client(cluster)

    ddc = DataDiscoveryCLI()
    ddc.do_regex_sites(r"T[123]_(CH|IT|UK|FR|DE)_\w+")
    ddc.load_dataset_definition(dataset_definition,
                               query_results_strategy="all",
                               replicas_strategy="round-robin")

    fileset_total = ddc.do_preprocess(output_file="fileset",
                      step_size=100000,  #chunk size for files splitting
                      align_to_clusters=False,
                      scheduler_url=client.scheduler.address)

```

and now the CLI is working even when `processes=True` in the cluster configuration.

**Comment by lgray** [comment]
Why is `freeze_support()` doing anything? It's only supposed to have any effect on windows.

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by mmarchegiani** [comment]
You are correct, if I comment out the call to `freeze_support()`, the script is also working. It does not make any difference.
Initially I was running the CLI without the `if __name__ == '__main__':` statement and I got the following error:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
so I followed the suggestion and try to run within the `if __name__ == '__main__':` statement. It turns out that running without `if __name__ == '__main__':` will trigger the creation of a child process with name `'__mp_main__'` before the `__main__` finishes its bootstrapping phase, resulting in a crash.

**Comment by lgray** [comment]
Ah yeah - the `if __name__ == "__main__":` guard is rather important here! It seems things are working correctly. I will close this issue.

**Comment by ikrommyd** [comment]
@mmarchegiani Always wrap your main execution inside `if __name__ == "__main__":`
