### ISSUE TITLE
Too many slashes in file urls from dataset_tools

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#1053]
**Describe the bug**
Using the new dataset query API through Rucio returns PFNs with one too many slashes, e.g.
```
│   ├── root://xrootd.cmsaf.mit.edu:1094///store/data/Run2018D/SingleMuon/NANOAOD/UL2018_MiniAODv2_NanoAODv9_GT36-v1/70000/5E570C94-EF7F-F64E-851B-AE9074B89A30.root
```
For some sites, such as MIT, this can cause strange opening/reading errors. Generally xrootd urls should have one or two slashes between the hostid and the path, e.g.
```
root://xrootd.cmsaf.mit.edu:1094//store/data/Run2018D/SingleMuon/NANOAOD/UL2018_MiniAODv2_NanoAODv9_GT36-v1/70000/5E570C94-EF7F-F64E-851B-AE9074B89A30.root
```
This may be site-specific, and perhaps is an issue on the Rucio client side.

**Comment by lgray** [comment]
@valsdav
