### ISSUE TITLE
json_lookup does not support dask_awkward processing

### ISSUE THREAD

**Issue by aapo-kossi** [scikit-hep/coffea#1108]
**Description**
`lookup_tools.json_lookup` has no support for dask_awkward arrays and the new processor scheme.

**To Reproduce**
Here is a minimal reproducible example, with actual data paths mimicked. 
```
from coffea.lookup_tools import extractor
from coffea.dataset_tools import apply_to_dataset, max_chunks, preprocess
import awkward as ak
import hist.dask as hist


pu_file = "pileup_2017.txt"
ext = extractor()
ext.add_weight_sets([f"pileup pileup {pu_file}"])
ext.finalize()

def process(events):
    print(len(events))
    events = events[ak.num(events.Tau,axis=1)==1]
    eva = ext.make_evaluator()
    pileup = eva["pileup"](events.run, events.luminosityBlock)
    pu_hist = hist.Hist.new.Reg(100,0,100,name="pileup").Double()
    pu_hist.fill(ak.Array(pileup))
    return {"count": ak.num(events.Tau,axis=0)}#, "pu": pu_hist}

def main():
    fileset = {
        "run": {
            "files": {
                (
                    "root://some-storage-element.io/TauRun_2017X_NanoAODv9/events_1.root"
                ): "Events",
            }
        }
    }
    fileset = preprocess(
        fileset,
        step_size=10
    )[0]
    fileset = max_chunks(fileset, 1)

    to_compute = apply_to_dataset(
        process,
        fileset["run"]
    )

if __name__ =="__main__":
    main()
```
Since json_lookup just iterates over the length of the runs array, it fails for the typetracers that are input when constructing the task graph. If the length of the arrays is undefined, a simple error is emitted, and in the situation that the sizes are static, an empty list is returned as the Dask Scalars cannot be found in the keys of the json object. Looking at the source code this is already quite obvious, but here is the error log:
```
Traceback (most recent call last):
  File "/ssd-home/aakoss/work/coffea_mre/main.py", line 46, in <module>
    main()
  File "/ssd-home/aakoss/work/coffea_mre/main.py", line 40, in main
    to_compute = apply_to_dataset(
                 ^^^^^^^^^^^^^^^^^
  File "/ssd-home/aakoss/miniforge3/envs/coffea2/lib/python3.11/site-packages/coffea/dataset_tools/apply_processor.py", line 83, in apply_to_dataset
    out = data_manipulation(events)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd-home/aakoss/work/coffea_mre/main.py", line 16, in process
    pileup = eva["pileup"](events.run, events.luminosityBlock)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd-home/aakoss/miniforge3/envs/coffea2/lib/python3.11/site-packages/coffea/lookup_tools/json_lookup.py", line 7, in __call__
    for i in range(len(run)):
                   ^^^^^^^^
  File "/ssd-home/aakoss/miniforge3/envs/coffea2/lib/python3.11/site-packages/dask_awkward/lib/core.py", line 984, in __len__
    raise TypeError(
TypeError: Cannot determine length of collection with unknown partition sizes without executing the graph.
Use `dask_awkward.num(..., axis=0)` if you want a lazy Scalar of the length.
If you want to eagerly compute the partition sizes to have the ability to call `len` on the collection, use `.eager_compute_divisions()` on the collection.
```

**Expected behavior**
The lookup for dask Arrays is dereffed to computation time, similarly to how lumi_tools is implemented. It is also ideally more efficient than iterating through each event in Python.

**Desktop (please complete the following information):**
 - OS: linux
 - Version 2024.5.0

**Comment by lgray** [comment]
@aapo-kossi - thank you for posting an issue. So that I can think about the correct course of action, what are you trying to do with the correction you're reading in as a json histogram?

**Comment by aapo-kossi** [comment]
It's used for calculating pileup for data samples, one use case is for jet correction analysis. In my own analysis this is actually not vital, I can use pileup distributions that are already available. Maybe @slehti can elaborate on details if needed, I only happened to notice this as I was migrating from an old version of coffea.

**Comment by lgray** [comment]
In this case I think I would suggest migrating that lookup table to correctionlib. The recursively defined json histograms are extremely inefficient for a variety of reasons. Where do you get that histogram from? If it's out of `brilCalc` you can also use `coffea.lumi_tools` to achieve your goals here, which are extremely fast and dask aware.

You can convert your json_histogram to a `hist` histogram (or to ROOT and then read it with uproot as `hist`, whatever you prefer, using this tool: https://github.com/cms-nanoAOD/correctionlib/blob/master/src/correctionlib/convert.py#L63

From there the standard dense lookup is dask aware!

Hope that helps!

**Comment by lgray** [comment]
@aapo-kossi does this path forward fix your problems? I would not like to continue supporting the (extremely slow) json lookup implementation that you are using, especially when suitable, optimized alternatives exist.

**Comment by aapo-kossi** [comment]
@lgray yes, the thank you for the reasonable suggestions for alternatives. I agree that the slow implementation does not need to exist here since there are already much better options, and it creates more confusion by still seemingly being available.

**Comment by lgray** [comment]
@aapo-kossi OK - this tool will be deprecated in a future release. Thanks! This issue will close with that PR merged.
