### ISSUE TITLE
n-minus-one cuts and cutflow generators are failing tests with numpy 2.0

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#1112]
@ikrommyd could you please have a look at this? It fails on all architectures and there are visible differences in the output arrays if you look at the failed CI runs.

<img width="781" alt="image" src="https://github.com/CoffeaTeam/coffea/assets/1068089/bcc4ce38-b90a-4ddd-a407-afdd57e36f80">

<img width="1004" alt="image" src="https://github.com/CoffeaTeam/coffea/assets/1068089/c884ef4d-e387-4021-b000-14d782175fb3">

Given that these are the first tests with numpy 2, somehow the problem stems from there. So this problem could easily be deeper in awkward, or in dask-awkward.

@jpivarski FYI

**Comment by lgray** [comment]
There appears to be a bug in the boost_histogram python bindings. Following up there.

For now I will pin numpy<2 for coffea.

**Comment by ikrommyd** [comment]
Hi Lindsey, just seeing this, do you still want me to check anything or is it definitely a boost-histogram problem?

**Comment by henryiii** [comment]
It might be related to the fact numpy is more picky about types now. You care trying to directly compare a floating point awkwardarray with a floating point histogram, I think? Floating point comparisons are poorly defined, I'd compare similarity or cast to int or something.

https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion

**Comment by henryiii** [comment]
DEBUG    fsspec.local:local.py:347 open file: /Users/runner/work/coffea/coffea/tests/samples/nano_dy.root


The logs are 99% this line repeated. If that could be reduced, that would be nice. :)

Maybe numpy.histogram no longer keeps the upper edge, like it used to?

**Comment by lgray** [comment]
It may not, we've got a missing count in the last bin in this case, is where the failure is coming from.

**Comment by lgray** [comment]
But there aren't any apparent changes in the docs.

**Comment by lgray** [comment]
Oh - it appears to be something different in overflow behavior. Fun.
