### ISSUE TITLE
LowPtElectron is missing in nanoaod methods and the schema

### ISSUE THREAD

**Issue by ikrommyd** [scikit-hep/coffea#1120]
`LowPtElectron` class should be added  in the nanoevents methods and to the nanoaod schema.

**Comment by lgray** [comment]
Is LowPtElectron part of standard NanoAOD these days?

**Comment by ikrommyd** [comment]
According to https://cms-nanoaod-integration.web.cern.ch/autoDoc and https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/lowPtElectrons_cff.py yes

**Comment by ikrommyd** [comment]
It's half the issue of [this thread in mattermost](https://mattermost.web.cern.ch/cms-exp/pl/uiuynox5nbn6zpm6azz19iupir) where I suggested `events.LowPtElectron = ak.with_name(events.LowPtElectron, "PtEtaPhiMCandidate")` as a partial solution but that won't give them global indices and systematics.

**Comment by lgray** [comment]
Yeah those need to be in the schema beforehand. I'll comment on mattermost.
