### ISSUE TITLE
Tracking uproot issue #1267

### ISSUE THREAD

**Issue by SamKelson** [scikit-hep/coffea#1164]
[This bug](https://github.com/scikit-hep/uproot5/issues/1267) which affects coffea has been fixed by [an uproot PR ](https://github.com/scikit-hep/uproot5/pull/1269). This issue is to ensure that when an uproot patch is released the corresponding uproot version needed for coffea is bumped.

ToDo:
- Bump version
https://github.com/CoffeaTeam/coffea/blob/4cc6b2577e1a00757977b518e67aa7733071ffb6/pyproject.toml#L41
- Enable previously disabled test
https://github.com/CoffeaTeam/coffea/blob/4cc6b2577e1a00757977b518e67aa7733071ffb6/tests/test_nanoevents_physlite.py#L32-L34
- Fix use of a mutable default
https://github.com/CoffeaTeam/coffea/blob/4cc6b2577e1a00757977b518e67aa7733071ffb6/tests/test_nanoevents_physlite.py#L50-L54

**Comment by alexander-held** [comment]
`uproot` 5.3.11 is now available: https://github.com/scikit-hep/uproot5/releases/tag/v5.3.11
