### ISSUE TITLE
Create a single job per multiple files when running with parsl

### ISSUE THREAD

**Issue by mcremone** [scikit-hep/coffea#117]
Modify derive_chunks:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/parsl/detail.py#L52
so that if n-entries < chunksize it will grab files together until it's larger than the chunksize.

Need also to take care of the fact that some 'items' that are returned by get_chunking might be a list of files rather than a single file string.

**Comment by lgray** [comment]
obsolete
