### ISSUE TITLE
Matching function factory

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/coffea#122]
**Is your feature request related to a problem? Please describe.**

Feature request to improve code interface.

**Describe the solution you'd like**

```python
dR_matcher = match_function_factory(deltaRCut=0.3)
jagged_gen.match(jagged_reco, dR_matcher)
```

**Describe alternatives you've considered**

No alternatives considered. I'm pretty stubborn.

**Additional context**

This makes it a bit more flexible and is very similar to how fastjet defines these things. This would also make the interface for function matching much easier to deal with by allowing different match functions to have different interfaces without affecting/rewriting the underlying matching code.

**Comment by lgray** [comment]
fixed in nanoevents nearest / metric_table
