### ISSUE TITLE
Adding an option to automatically skip failed to read files in processor

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#135]
**Is your feature request related to a problem? Please describe.**
Reading xrootd files, sometimes a file or two gets corrupted or just not readable via xrootd temporarily. This currently throws an error possibly wasting time and makes me continuously update the file dictionary I'm feed it.

**Describe the solution you'd like**
Adding a flag to the processor/run_uproot_job to instead skip a file if it's unreadable and maybe record the numbers and names of the skipped file to print at the end so the user can decide if to ignore it or fix it.

**Comment by lgray** [comment]
@andrzejnovak what error does it throw when it gets a corrupted file? if you can give me an example I can probably cook something up super quick.

**Comment by andrzejnovak** [comment]
Right 
```
~/software/miniconda3/lib/python3.7/site-packages/uproot/source/xrootd.py in _open(self)
     32             status, dummy = self._source.open(self.path, timeout=(0 if self.timeout is None else self.timeout))
     33             if status.get("error", None):
---> 34                 raise OSError(status["message"])
     35             status, info = self._source.stat(timeout=(0 if self.timeout is None else self.timeout))
     36             if status.get("error", None):

OSError: [ERROR] Server responded with an error: [3014] Unable to open file  /eos/cms/store/group/phys_btag/BoostedBTag/BTagNTuples/2017/9_4_X_v04_20190701/GluGluHToCC_M125_LHEHpT_250-Inf_13TeV_amcatnloFXFX_pythia8/crab_GluGluHToCC_M125_LHEHpT_250-Inf_13TeV_amcatnloFXFX_pythia8_9_4_X_v04_20190701/190701_095327/0000/JetTree_mc_FatJets_Subjets_BoostedCommissioning_201.root; Network is unreachable
```
