### ISSUE TITLE
JetMet txt_converters creates invalid jagged array

### ISSUE THREAD

**Issue by jpata** [scikit-hep/coffea#143]
**Describe the bug**
Thanks for the nice JME tools! I wanted to report the following issue while I also debug it, perhaps we can find the solution faster :)

`coffea.lookup_tools.extractor` produces an incorrect internal jagged array on the official JME file [Summer16_07Aug2017_V11_L1fix_MC_L2Relative_AK4PFchs.txt](https://github.com/CoffeaTeam/coffea/files/3400289/Summer16_07Aug2017_V11_L1fix_MC_L2Relative_AK4PFchs.txt) (added for reference) with the following error:
`ValueError: maximum offset 2498 is beyond the length of the content (2497)`

**To Reproduce**

Run the following
~~~
from coffea.lookup_tools import extractor

extract = extractor()
extract.add_weight_sets(['* * Summer16_07Aug2017_V11_L1fix_MC_L2Relative_AK4PFchs.txt'])
extract.finalize()
extract.make_evaluator()
~~~

To induce the crash at init-time rather than eval-time: 
~~~
diff --git a/coffea/lookup_tools/txt_converters.py b/coffea/lookup_tools/txt_converters.py
index 73a49ec..26de60e 100644
--- a/coffea/lookup_tools/txt_converters.py
+++ b/coffea/lookup_tools/txt_converters.py
@@ -146,7 +146,9 @@ def _build_standard_jme_lookup(name, layout, pars, nBinnedVars, nBinColumns,
     parm_order = []
     offset_col = 2 * nBinnedVars + 1 + int(not interpolatedFunc) * 2 * nEvalVars
     for i in range(nParms):
-        parms.append(awkward.JaggedArray.fromcounts(jagged_counts, pars[columns[i + offset_col]]))
+        jag = awkward.JaggedArray.fromcounts(jagged_counts, pars[columns[i + offset_col]])
+        assert(jag._valid())
+        parms.append(jag)
         parm_order.append('p%i' % (i))

     wrapped_up = {}
~~~

**Expected behavior**
It works with the older supplied JME files, so it looks like either the JME file is bugged or the parser produces incorrect output.

**Output**

~~~
  File "test_jme.py", line 4, in <module>
    extract.add_weight_sets(['* * data/Summer16_07Aug2017_V11_L1fix_MC_L2Relative_AK4PFchs.txt'])
  File "/Users/joosep/Documents/caltech/hepaccelerate-cms/coffea/coffea/lookup_tools/extractor.py", line 75, in add_weight_sets
    self.import_file(thefile)
  File "/Users/joosep/Documents/caltech/hepaccelerate-cms/coffea/coffea/lookup_tools/extractor.py", line 100, in import_file
    self._filecache[thefile] = file_converters[theformat][thetype](thefile)
  File "/Users/joosep/Documents/caltech/hepaccelerate-cms/coffea/coffea/lookup_tools/txt_converters.py", line 163, in _convert_standard_jme_txt_file
    return _build_standard_jme_lookup(*_parse_jme_formatted_file(jmeFilePath))
  File "/Users/joosep/Documents/caltech/hepaccelerate-cms/coffea/coffea/lookup_tools/txt_converters.py", line 150, in _build_standard_jme_lookup
    assert(jag._valid())
  File "/Users/joosep/anaconda3/lib/python3.6/site-packages/awkward/array/jagged.py", line 439, in _valid
    raise ValueError("maximum offset {0} is beyond the length of the content ({1})".format(self._offsets.max(), len(self._content)))
ValueError: maximum offset 2498 is beyond the length of the content (2497)
~~~

**Desktop (please complete the following information):**
~~~
$ python --version
Python 3.6.7 :: Anaconda custom (64-bit)
$ uname -a
Darwin dhcp-112-136.caltech.edu 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
>>> awkward.__version__
'0.11.1'
coffea revision e776a80762ec17ea9bc05c35f5019d4edc04f091
~~~

**Additional context**
I believe the issue is happening here when creating `jagged_counts`, but so far I haven't traced it down exactly: https://github.com/CoffeaTeam/coffea/blob/master/coffea/lookup_tools/txt_converters.py#L136

**Comment by lgray** [comment]
Thanks for the catch, I'll try to look into this today!

**Comment by lgray** [comment]
@jpata looking at the JEC file the offending line is this:
```
          4.363          4.538          0.001        4.13166              7        3.62361        4.13166         1.0947        3.62361       0.294026     -0.0777143     -0.0646821
          4.363          4.538        4.10331        4.64103              7        4.10331        4.64103        1.22317        4.10331        0.17941     -0.0712989     -0.0225963
```

The for eta bin [ 4.363, 4.538] first pT bin is [0.001, 4.13166] and the second is [4.10331, 4.64103] which means the bins are somehow overlapping. Which seems malformed to me?

@aperloff any idea on how this is handled in the standard jetmet code?

**Comment by aperloff** [comment]
That is highly unusual and shouldn't normally happen. You should send a message to the JERC conveners and tell them that the file is messed up. I'm actually a little surprised it was even possible to make a file like this. However, the standard JetMET code is probably fine because it is looking for monotonically increasing lower bin boundaries, so this will not trip it up.

This is the relevant function in JetCorrectorParametersHelper: https://github.com/cms-sw/cmssw/blob/master/CondFormats/JetMETObjects/src/JetCorrectorParametersHelper.cc#L144-L195

**Comment by lgray** [comment]
@aperloff can you explain the latter a bit more? 

Do you mean that it contructs bins based only on the low bin edges and the final upper edge or something like that?

**Comment by aperloff** [comment]
Yes, exactly. When a text file is read in, a map is constructed which contains the lower bin boundaries as keys. When looking for the line that a specific jet corresponds to, it checks the std::lower_bound of each dimension. So the upper bounds are not really taken into account, except for the last one.

**Comment by lgray** [comment]
Alright cool.

I'll make our code operate in that way, right now I assumed the bin-edges were value equal so I could make a union of the upper and lower edges. This little instance breaks that.

I'll have the code emit a warning when this occurs.

@jpata sound OK?

**Comment by aperloff** [comment]
In theory you are right, the upper bin edge of one bin should be equal to the lower bin edge of the next. I guess I should have put a check for this in the JetCorrectorParameter code during the initialization step (when the map is being created). You could always add one so that this case doesn't crop up in the future.

**Comment by jpata** [comment]
Thanks very much for investigating it fast! Having the same behaviour as the CMSSW JME code, along with a warning for unexpected bins, sounds like a great solution. Shall I send this thread to the JME hypernews so they can have a look at the JEC file creation upstream?

**Comment by lgray** [comment]
Yeah, please send this to JME HN and I'll have a PR to reference as well posted momentarily.

**Comment by jpata** [comment]
For the record, here is the report to JME: https://hypernews.cern.ch/HyperNews/CMS/get/jes/876.html
