### ISSUE TITLE
Create a coffea users mailing list.

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#145]
That is administrated by cms-coffea egroup.

**Comment by areinsvo** [comment]
@lgray I created the cms-coffea-users group and set it to be administrated by cms-coffea. I'm not sure if there is a way to automatically add the members of cms-coffea to the new list. 

Let's keep this issue open until I have a chance to advertise the new list and update the documentation.

**Comment by lgray** [comment]
@areinsvo You can put an egroup in an egroup, and it won't duplicate mails, so just plunk cms-coffea into the members list of cms-coffea-users.

**Comment by areinsvo** [comment]
I tried but I can't find that option. Since you're in cms-coffea you should be an admin for cms-coffea-users if you'd like to try it. Unless @mcremone can act as the cms-coffea admin and subscribe everyone to cms-coffea-users.

**Comment by lgray** [comment]
@areinsvo ah, the way I was able to get that to work was with a static egroup (which have a dynamic user list, ???). I'd delete the egroup and reform it as static then it's easier to control the membership. The dynamic egroup membership controls are from some other planet, at least to me.

**Comment by nsmith-** [comment]
This can be closed, right?
