### ISSUE TITLE
Log and sqrt functions in btag scale factor formulas

### ISSUE THREAD

**Issue by dnoonan08** [scikit-hep/coffea#148]
Functions such as log and sqrt show up in the btagging SF formulas for DeepCSV in 2017 & 2018, which break the extractor.  Using a csv with these types of formulas in the lookup_tools extractor results in a KeyError for 'log' in the make_evaluator step:

```
from coffea.lookup_tools import extractor
ext = extractor()
ext.add_weight_sets(["btag * DeepCSV_102XSF_V1.csv"])
ext.finalize()
evaluator = ext.make_evaluator()
```

If the log and sqrt functions are replaced in the .csv with np.log and np.sqrt, it works fine.

**Comment by lgray** [comment]
@dnoonan08 can you point me to some of the files? This can likely be fixed quickly.

**Comment by dnoonan08** [comment]
The file I'm using was from here:
https://twiki.cern.ch/twiki/pub/CMS/BtagRecommendation102X/DeepCSV_102XSF_V1.csv

**Comment by lgray** [comment]
@dnoonan08 this is now fixed in master, go ahead and try it. A proper release will appear later today.
