### ISSUE TITLE
JECs need validation against the official implementation

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#15]
Validate our JEC implementation against: https://twiki.cern.ch/twiki/bin/viewauth/CMS/JERCReference

**Comment by jpata** [comment]
I wanted to mention here that I cross-checked the results from the JEC (nominal correction, no uncertainties yet) in detail against the JetRecalibrator in nanoaod-tools and got perfect closure!

However, I did notice a small feature in coffea that may lead to unintented consequences: 

```python
FactorizedJetCorrector.getCorrection(JetPt=raw_pt, ...)
```

will modify the original `raw_pt` vector in place!

**Comment by lgray** [comment]
@jpata ahh nice bug. I'll patch it up in a bit.

**Comment by lgray** [comment]
Fixed by @aperloff in #483
