### ISSUE TITLE
plot1d density argument doesn't work right

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#152]
I get taken from left to right by adding `density=True` flag and the y-axis doesn't look like it's normalized to 1 as expected.

<p float="center">
  <img src="https://user-images.githubusercontent.com/13226500/61800245-e842d980-ae2c-11e9-8644-6e04a6764ccf.png" width="300" /> 
  <img src="https://user-images.githubusercontent.com/13226500/61800186-cd706500-ae2c-11e9-8065-c1770fb025db.png" width="300" />
</p>

**Comment by lgray** [comment]
@nsmith-  this one is all you :-)

**Comment by andrzejnovak** [comment]
Actually here's a mre 
```
A = hist.Hist("Counts", hist.Cat("dataset", "Dataset") , hist.Bin("mass", r"$m_{jet}$ [GeV]", 20, 0, 180))
A.clear()
masses = np.linspace(0.1,179.99,200)
A.fill(mass=masses, dataset="test")

num = A.project('dataset', 'test')
num.scale(1./num.sum('mass').values()[()])
vnum = num.values()[()]
print(vnum)

fig,ax, _ = plot.plot1d(A,density=True, overlay='dataset')
ax.hlines([0.05],0,1)
plt.show()

```

with a strange looking output 
![image](https://user-images.githubusercontent.com/13226500/61809622-fe0cca80-ae3d-11e9-82f6-af86e7e5e045.png)

**Comment by nsmith-** [comment]
Well now that I see the x axis, this isn't a bug: the density is a probability density, satisfying the condition that the integral over the support is 1.  Here, indeed 0.0058*(179.99-0.1)~=1

If you are looking for "fraction in bin" semantic, then currently there is no direct support for that in the plotting routine.  A short fix is to pre-scale the histogram: `h.Scale(1/h.sum(*h.axes)[()])`
