### ISSUE TITLE
 Adding legend settings forwarding to coffea.hist.plot1d

### ISSUE THREAD

**Issue by phylsix** [scikit-hep/coffea#156]
**Is your feature request related to a problem? Please describe.**
Sometimes the default legend settings are not satisfactory, adjusting them after they are created requires additional code(grouping the handles), but easy to add when constructed, I though it would be convenient to add another kwarg for legend settings when calling `coffea.hist.plot1d`. Or something for this already exists?

**Describe the solution you'd like**
Add additional kwarg to the plot1d signature, something like legend_opts=None, and forward that when calling ax.legend().

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nsmith-** [comment]
Seems like a reasonable thing to forward.  Is this strictly for legend styling and placement, or also to adjust things like labels?  For the latter, it might be worth knowing that each axis identifier has a `label` property that allows one to override the default legend label (usually the bin name).
e.g.
```python
labels = {'dataset1': 'A fancy name', 'dataset2': 'another name'}
for bin in h.axis('dataset').identifiers():
    bin.label = labels[bin.name]
```
and similarly for `Bin()` axis types

**Comment by phylsix** [comment]
what prompts me to raise this issue is the styling and placement of the legend (multiple columns, outside of ax, etc). Good to know how to change the label of hist axes, thanks!

**Comment by andrzejnovak** [comment]
For now you can try  to mod the rcParams with styles `plt.style.use({'legend.fontsize':15, "font.size": 20}) `or you might be able to do it with context as `with plt..style.use([cms.ROOT, {'legend.fontsize':15, "font.size": 20}])`
