### ISSUE TITLE
hist.fill kwargs not guarded

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/coffea#197]
**Describe the bug**

The histogram fill function can be called with arbitrary keyword arguments. Unless there are very strong reasons for this, I think it is dangerous. A simple typo can send optional arguments like `weight` into a void. 

**To Reproduce**
```python
import numpy as np
from coffea.hist import Bin, Cat, Hist

dataset_ax = Cat("dataset", "Primary dataset")
pt_ax = Bin("pt", r"pt", 5, 0, 5)

h = Hist(
        "Counts",
        dataset_ax,
        pt_ax,
        )

h.fill(
    pt=np.array([1,2,3]),
    dataset='test',
    wieght=np.array([4,5,6]) # I mis-spelled "weight"
)
```

**Expected behavior**
Fill should raise an exception if an unknown kwarg is provided.

**Comment by AndreasAlbert** [comment]
ok, filing this as a bug rather than a feature request may have been an emotional overreaction on my part ;) Feel free to reclassify

**Comment by nsmith-** [comment]
I imagine this behavior was noticed after much pain... so lets call it a usability bug.
