### ISSUE TITLE
Implement MET Corrections

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#21]

**Comment by mcremone** [comment]
Do you have a reference in how this is done in bacon?

**Comment by mcremone** [comment]
JetMet corrector for NanoAOD to be used as reference: https://gitlab.cern.ch/mcremone/NanoTrees/blob/master/python/helpers/jetmetCorrector.py

**Comment by lgray** [comment]
@mcremone This may depend on #17, #23, and #28. IIRC there's some jet smearing and stuff done when making the MET systematics. 

We should follow the JME pog recipe to the fullest extent.

**Comment by nsmith-** [comment]
Honestly this is best done in NanoAOD/BaconProd.  The JME official recipe is this file: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
But in principle it is just propagating the JES and JER effects to MET, although the jet collection is cleaned by a nonstandard cut (`L1441` of the above)

**Comment by lgray** [comment]
For bacon they just take the type-1 corrections:

https://github.com/DAZSLE/BaconAnalyzer/blob/fead076cfadac4d568002134a7a58a1bce0f1203/Analyzer/src/JetLoader.cc#L270-L286

**Comment by lgray** [comment]
Type 1 MET corrections are implemented in JetTransformer as part of applying JECs and related uncertainties:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/jetmet_tools/JetTransformer.py#L209

We probably want a better way to deal with this in the future.
