### ISSUE TITLE
Allow plot1d to use markers correctly

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#210]
**Is your feature request related to a problem? Please describe.**
I would like to plot a histogram using markers only. Unfortunately supplying `line_opts={"marker": "o", "linestyle": "None"}` to plot1d places the markers on the left edge of the bins, while they should be at their centers. I was not able to find a way to make it working. Supplying `"where": "mid"` does not help, as the `x` values supplied to matplotlib by coffea are still the same.

**Describe the solution you'd like**
It would be nice if the placement could be controlled by the `where` property. One could also consider always using `mid` as value for `where` or internally setting the value of `where` correctly depending whether markers are requested.

**Comment by jrueb** [comment]
If there is really no way to make the markers work right now and if you would like, I could contribute with a pull request for this.

**Comment by andrzejnovak** [comment]
You should be able to pass it into `error_opts`. See https://github.com/CoffeaTeam/coffea/blob/master/binder/plotting-demo.ipynb

**Comment by nsmith-** [comment]
Yeah `error_opts` with errorbar disabled should do the trick.
Perhaps the naming here is getting in the way--the real difference between `line_opts` and `error_opts` is one is for drawing something between bin *edges* while the other is for drawing something at bin *centers*.

**Comment by jrueb** [comment]
Thanks, using error_opts instead works nicely.
