### ISSUE TITLE
backward non-compatible change to hist.plot1d return value 

### ISSUE THREAD

**Issue by belforte** [scikit-hep/coffea#214]
**Describe the bug**
https://github.com/CoffeaTeam/coffea/blob/5eda3869f046a30dbebba96cf1fdaaf06a8e7e6d/coffea/hist/plot.py#L278
is not compatible anymore with the documentation
https://github.com/CoffeaTeam/coffea/blob/5eda3869f046a30dbebba96cf1fdaaf06a8e7e6d/coffea/hist/plot.py#L163-L168

and causes e.g. this nbook to fail
https://github.com/prasanthkothuri/swan-spark-notebooks/blob/master/muonspectrum_v3_spark.ipynb

was this a typo, or an intentional break of backward compatibility ?
If it was intentional, how can now the user code access the matplot FIG object to manipulate it ?

**To Reproduce**
self evident

**Expected behavior**
1. code matches documentation 
2. public interface of widely used classes like "plot" is stable

**Comment by nsmith-** [comment]
@andrzejnovak what motivates only returning `ax` from the `hist.plotXXX` operations rather than the previous `fig, ax`?

**Comment by nsmith-** [comment]
Ok actually I remember we talked about dropping this.  I guess the thing to do is clean up docs/tutorials for lack of `fig` and maybe mention that one can retrieve the figure with `ax.figure`.

**Comment by belforte** [comment]
thanks for the `ax.figure` tip. I can make the expected plot now !

Do not know if it matters, but note that `plotgrid` still returrns
'fig, axes'

FWIW I like the (admittedly slowing down) practice of opening
an issue first, so that one states what and why, then making
a PullRequest (which ideally another person reviews).
Directly committing to master should be reserved for exceptionally
simple changes.

Guess it depends on the stage of the project

**Comment by andrzejnovak** [comment]
Hmm let me update the docs. The reason for this change was to bring it in line with other popular plotting libraries on top of `mpl` such as `seaborn`. `plotgrid()` should probably be returning an array of axes https://github.com/pandas-dev/pandas/blob/v0.25.3/pandas/plotting/_core.py#L594 

Indeed `fig` can be obtained as `ax.figure` and primitives can be fetched from `ax` either specifically like `ax.lines` and `ax.patches` or en masse as `ax.get_children()`

**Comment by lgray** [comment]
I'll talk to Pransath to get the notebook on swan updated early next week.
