### ISSUE TITLE
Implement good-run-list from JSON (make sure we can mask a Jagged array with it too)

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#22]

**Comment by lgray** [comment]
@mcremone Any progress on getting this out?

**Comment by nsmith-** [comment]
Ah I did this for the Z peak at some point.  It is here: https://github.com/CoffeaTeam/fnal-column-analysis-tools/blob/master/fnal_column_analysis_tools/lumi_tools/__init__.py#L36
Did not investigate using jagged methods to perform lookup.  Its reasonably fast as-is

**Comment by lgray** [comment]
Ah, thanks. Yeah, I haven't minded the issues in a bit. Many have been solved.

This was added in #45
