### ISSUE TITLE
plot1d to automatically pick overlay if only one categorical and one dense axis present

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#222]

**Comment by nsmith-** [comment]
What if one wants a multi-bar graph per category, where each bar color is a dense bin?

**Comment by nsmith-** [comment]
Note that is also not implemented yet, but could be.
e.g. https://matplotlib.org/3.1.1/gallery/lines_bars_and_markers/barchart.html

**Comment by andrzejnovak** [comment]
I guess that should be a different function

**Comment by andrzejnovak** [comment]
hmm or a flag for sth like `overlay_method` ?
