### ISSUE TITLE
Hist.rebin gives invalid results

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#247]
**Describe the bug**
coffea.hist.Hist.rebin gives invalid results

**To Reproduce**
```
import coffea.hist

axis = coffea.hist.Bin("x", "x", 20, -1, 1)
hist = coffea.hist.Hist("Counts", axis)
hist.fill(x=axis.centers())
new_axis = coffea.hist.Bin("x", "x", 10, -1, 1)
rebinned = hist.rebin(axis, new_axis)
print(rebinned.values())
```

**Expected behavior**
Output should be `{(): array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])}`

**Output**
`{(): array([3., 1., 2., 2., 2., 2., 2., 2., 2., 2.])}`

 - Coffea version 0.6.28

**Comment by nsmith-** [comment]
The bug is due to floating point representation issues:
```python
In [33]: (-0.8 - -1.) * 20 / (1. - -1.)
Out[33]: 1.9999999999999996

In [36]: np.floor(_33)
Out[36]: 1.0
```
A naive fix might be to add eps to the result before `floor`, yet a) this makes some other set of numbers map incorrectly, and b) in this case the precision loss is actually enough to need 2*eps:
```python

In [46]: np.floor(_33 + np.finfo(_33).eps)
Out[46]: 1.0

In [47]: np.floor(_33 + 2*np.finfo(_33).eps)
Out[47]: 2.0
```

Since the intention here is simply to merge bins, I'll solve this by adding the feature `hist.rebin(old_axis, axis_or_num)` where if `axis_or_num` is an integer, the axis will be rebinned correctly to have `nbins // num` bins

**Comment by jrueb** [comment]
It would be nice if `axis_or_num` could also be an iterable, so one could specify a variable number of bins that get merged into one. E.g. `[2,3,4]` would merge the first two, then the next three and then the next four, resulting in three new bins from 2+3+4=9 old bins.

**Comment by jrueb** [comment]
I would also like to point out that the documentation of `rebin()` isn't quite clear in that it doesn't mention that it returns a new histogram instead of modifying `self`.

**Comment by nsmith-** [comment]
For the multi-bin rebinning, one could also use
```python
new_edges = old_axis.edges()[np.cumsum([0, 2, 3, 4])]
new_axis = hist.Bin(old_axis.name, old_axis.label, new_edges)
```
That is, if the behavior of rebin respected the bin boundaries properly, which I'll see if I can arrange as well.

**Comment by nsmith-** [comment]
So in the end I decided against allowing variable number of merged bins, as it introduces some ambiguity: one might equally be justified in expecting `h.rebin('old', [1, 2, 3])` to rebin such that `[1, 2, 3]` is the new edges array.  Still, the method I proposed above works.

**Comment by jrueb** [comment]
Okay, it is indeed ambiguous. I realized that if `h` is 3-dimensional, one could also expect `h.rebin('old', [1, 2, 3])` to rebin the first axis to one bin, second axis to two, etc. I think this is a good solution.
