### ISSUE TITLE
tailtimeout default is not None in pre-executor

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#248]
Based on the line https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L638 it appears that all pre-executor jobs will timeout.  Should this be `None`?

A workaround would then be
```python
run_uproot_job(..., pre_args={'tailtimeout': None})
```

While here, the line https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L592 is inaccurate, as `tailtimeout` is normally passed on to executors and not interpreted by `run_uproot_job` itself.

**Comment by nsmith-** [comment]
Also, the warning `Stopped job early` might be clarified to suggest it is related to the `tailtimeout` setting

**Comment by nsmith-** [comment]
@dntaylor

**Comment by dntaylor** [comment]
Ah, sorry about that. Yes, it should be `None` by default. I stopped testing things without the tailtimeout set to a value so missed this.

**Comment by nsmith-** [comment]
Fixed in #250 
Can we cut a release @lgray ?

**Comment by lgray** [comment]
Please do!
