### ISSUE TITLE
Add GenPart mass in NanoEvents

### ISSUE THREAD

**Issue by dntaylor** [scikit-hep/coffea#252]
In NanoAOD, the GenPart mass is not store for SM particles less than 10 GeV.
This should be set automatically when build NanoEvents.

What I have been doing:
```
        # need to set the mass for SM particles
        masses = {
            11: 0.510998e-3,
            13: 0.105658,
            15: 1.77686,
        }
        for pdgId in masses:
            df['GenPart_mass'][abs(df['GenPart_pdgId'])==pdgId] = masses[pdgId]
        events = NanoEvents.from_arrays(df)
```

But, would need a more exhaustive list.

See documentation here: **https://cms-nanoaod-integration.web.cern.ch/integration/master-102X/mc102X_doc.html#GenPart**

**Comment by dntaylor** [comment]
@nsmith-

**Comment by dntaylor** [comment]
Here is where they specify which are kept:
https://github.com/cms-nanoAOD/cmssw/blob/master-cmsswmaster/PhysicsTools/NanoAOD/python/genparticles_cff.py#L44

**Comment by nsmith-** [comment]
We never did add back masses in NanoEvents, but rather now the list of particles with zeroed out masses is restricted to 40 as documented in the cms-nanoAOD issue mentioned above.

**Comment by lgray** [comment]
I suppose it wouldn't be too hard to add back in manually, aside from various BSM scenarios which appear to be better handled in the PRs to nanoAOD.
