### ISSUE TITLE
A bug was found in coffea.lookup_tools.evaluator.btag_csv_scalefactors

### ISSUE THREAD

**Issue by irenedutta23** [scikit-hep/coffea#264]
**Describe the bug**
I noticed that the B tag evaluator crashes while trying to implement the new TuneCP5 btag shape scale factors (DeepCSV_2016LegacySF_V1_TuneCP5.csv) from here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy

It also fails while trying to evaluate the new 2017 V5 scale factors (DeepCSV_94XSF_V5_B_F.csv) from here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X

**To Reproduce**
I have made a PR
https://github.com/CoffeaTeam/coffea/pull/263

**Expected behavior**
The extractor doesn't parse the file properly and crashes. 

**Output**

`File "../coffea/coffea/lookup_tools/csv_converters.py", line 57, in convert_btag_csv_file
    vals[k, j, i] = corrections[this_bin][columns[10]][0]
IndexError: index 0 is out of bounds for axis 0 with size 0`

**Comment by nsmith-** [comment]
@irenedutta23 can you test coffea v0.6.33 and close this if things look ok?

**Comment by irenedutta23** [comment]
Hi @nsmith
 I was checking this version today and I noticed that if I try 
~~~
sf_evaluator = BTagScaleFactor("data/btagSF/DeepCSV_2016LegacySF_V1.csv", BTagScaleFactor.RESHAPE, 'iterativefit', keep_df=True)
sf_evaluator.eval('up_cferr2',4,2.3,30,0.02,True)

*** KeyError: 'up_cferr2'
~~~~
I see the same issue for `cf_err1`. From what I understand, when one uses the iterative fit method, the following systematics corresponds to the given flavours:

- bFlav - jes, lf, hfstats1, hfstats2                                                                                                                                                                          
- cFlav - cferr1, cferr2                                                                                                                                                                                       
- lFlav - jes, hf, lfstats1, lfstats2 
I know that the `up_cferr2` definitely exists in the .csv files and was accessible using the old coffea btag evalautor
Do you know what's the issue here? Is this something that I'm doing wrong?

**Comment by nsmith-** [comment]
Since the measurement type can differ for each flavor, you should specify all three in the methods field, i.e. `iterativefit,iterativefit,iterativefit`. Perhaps we could make it assume all the same, although often there is no common method for all three flavors.
```python
sf = BTagScaleFactor('tests/samples/DeepCSV_2016LegacySF_V1_TuneCP5.btag.csv.gz', BTagScaleFactor.RESHAPE, 'iterativefit,iterativefit,iterativefit')
sf.eval('up_cferr2',4,2.3,np.array(30.),0.02,True)
```

**Comment by irenedutta23** [comment]
I see, thanks! This resolves my problem. I'll close this issue.
