### ISSUE TITLE
Exception when trying to extract JER SF

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#265]
**Describe the bug**
I'm getting a ValueError when trying to load the JER SF using `coffea.lookup_tools.extractor`

**To Reproduce**
Download the SF file from https://github.com/cms-jet/JRDatabase/blob/master/textFiles/Autumn18_V7b_MC/Autumn18_V7b_MC_SF_AK8PFchs.txt and change extrension to .jersf.txt. Then run
```
import coffea
ext = coffea.lookup_tools.extractor()
ext.add_weight_sets(["* * Autumn18_V7b_MC_SF_AK4PFchs.jersf.txt"])
```

This will raise `ValueError: too many values to unpack (expected 3)`.

**Comment by lgray** [comment]
Probably a file format difference. Seems to be trending in CMS these days. I'll take a look at it today.

**Comment by lgray** [comment]
@jrueb Do you need the new JERSF split variations or just the total variation?
If it's the former I have a fix now. The latter requires an updated treatment in the jet transformer as well.

**Comment by jrueb** [comment]
For now, I only need the total. For the future, I can not rule out that this might be different.

**Comment by lgray** [comment]
@jrueb OK - cool. I'll try to have a fix for the rest soon, need to talk to JME about how the additional smearings are dealt with.

Original fix took a while because I was stuck writing a grant proposal. Feel free to contribute fixes to stuff like this in the future!
