### ISSUE TITLE
Yet another histogramming standard

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#27]
* Stack pretty stack plots
* The errors bars should be correct
* Should be able to read in from and output to uproot.
   * Maybe pandas and other things too

**Comment by lgray** [comment]
Being addressed in #26

**Comment by nsmith-** [comment]
uproot doesn't yet support output, I will make a pyROOT exporter (which in principle should only `import ROOT` if you call that function)

**Comment by lgray** [comment]
I thought Jim had some apparatus in histbook writing out root or root-via-pandas compatible stuff?

**Comment by nsmith-** [comment]
@jpivarski is this a current or planned feature? (writing TH1, TH2 I guess would be sufficient)

**Comment by jpivarski** [comment]
This is the mapping from Python objects to ROOT objects: https://github.com/scikit-hep/uproot-methods/blob/master/uproot_methods/convert.py

It refers to such functions as `uproot_methods.classes.TH1.from_numpy`. This is the beginning of conversion code, with "uproot bags" (objects with attributes that have `._f*` names) as the intermediate format. Eventually, this will be replaced by https://github.com/diana-hep/portally as a histogram converter (though the uproot-methods conversion service will still be needed for non-histograms).
