### ISSUE TITLE
Running Four Muon Spectrum with Iterative Executor

### ISSUE THREAD

**Issue by eestr** [scikit-hep/coffea#274]
**Describe the bug**
I wanted to run the Four Muon Spectrum (https://coffeateam.github.io/coffea/notebooks/muonspectrum_v4.html) with coffea.processor.iterative_executor instead of coffea.processor.futures_executor. When I make the changes to the example (shown below), I get an error of the following type: raise ValueError("maximum offset {0} is beyond the length of the content ({1})".format(self._offsets.max(), len(self._content)))

**To Reproduce**
1. Copy Four Muon Spectrum code into file
2. create directory named 'data' in same directory as code. download data files into 'data' directory
3. Edit this section to be the following:
output = processor.run_uproot_job(fileset,
                                  treename='Events',
                                  processor_instance=FancyDimuonProcessor(),
                                  executor = processor.iterative_executor
                                  # executor=processor.futures_executor,
                                  # executor_args={'workers': 6, 'flatten': True},
                                  # chunksize=500000,
                                 )
4. Run code

**Expected behavior**
I expected the program to run the same way as it had with coffea.processor.futures_executor

**Output** (more detailed error message)
Traceback (most recent call last):
   File "four_muon_spectrum_test.py", line 45, in process
    soft_id = (muons.softId > 0)
  File "~/miniconda3/envs/blah/lib/python3.6/site-packages/coffea/analysis_objects/JaggedCandidateMethods.py", line 480, in __getattr__
    return self[what]
  File "~/miniconda3/envs/blah/lib/python3.6/site-packages/awkward/array/jagged.py", line 510, in __getitem__
    self._valid()
  File "~/miniconda3/envs/blah/lib/python3.6/site-packages/awkward/array/jagged.py", line 469, in _valid
    raise ValueError("maximum offset {0} is beyond the length of the content ({1})".format(self._offsets.max(), len(self._content)))
ValueError: maximum offset 252533 is beyond the length of the content (99938)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Kernel Release: 3.10.0-1062.12.1.el7.x86_64

**Comment by andrzejnovak** [comment]
@eestr does it also not run when you uncomment the flatten arg?

**Comment by andrzejnovak** [comment]
@eestr yup, I just tested it, though we should update the plot signatures

**Comment by eestr** [comment]
That worked, thank you!

**Comment by andrzejnovak** [comment]
@nsmith- Should you edit the example notebook to explain the kwarg or relabel this issue as community-support?

**Comment by nsmith-** [comment]
The issue here is that the `flatten` argument appears in executor configuration, far away from the data processor declaration, so one gets confused about what it is doing and why, in this case, it is necessary. I think in the long term we need a refactoring of the processor stuff.
