### ISSUE TITLE
Add rho as an event variable instead of jet variable in JetTransformer

### ISSUE THREAD

**Issue by dnoonan08** [scikit-hep/coffea#275]
In the JetTransformer, the rho value used in the jet energy corrections is expected to be a jet property (inside the jet JaggedCandidateArray) rather than an event level variable.  The workaround I made in my code was to add rho as the same value in all jets of an event:
```
rho = df['fixedGridRhoFastjetAll']
jets['rho'] = jets.pt.ones_like()*rho
```
I think it would be good to have the rho value be passed as another argument to the JetTransformer.transform() function on it's own as an event variable, rather than part of the jet array.

**Comment by lgray** [comment]
Fixed/automated in CorrectedJetsFactory
