### ISSUE TITLE
Extending jetmet_tools to interface with NanoEvents

### ISSUE THREAD

**Issue by mcremone** [scikit-hep/coffea#280]
To use the jetmet_tools it is currently required to have a JaggedCandidateArray in input:

https://github.com/CoffeaTeam/coffea/blob/master/coffea/jetmet_tools/JetTransformer.py#L124

would be good to adapt this to accept NanoEvents.

**Comment by lgray** [comment]
This is fixed in #364 with the CorrectedJetFactory and CorrectedMETFactory.

However, it requires updating to awkward 1.0.
