### ISSUE TITLE
"binwnorm" argument to plot1d does not seem to work

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/coffea#288]
**Describe the bug**
It seems that the `binwnorm` argument to `plot1d` does not do anything. 

**To Reproduce**
Minimal working example:
```python
from coffea.hist import Hist, Bin, plot1d
import numpy as np

pt_ax = Bin("pt","pt",10,0,100)
pt_hist1 = Hist("pt_hist",pt_ax)
pt_hist2 = Hist("pt_hist2",pt_ax)
pt_hist3 = Hist("pt_hist2",pt_ax)

pt_hist1.fill(pt=100*np.random.rand(1000))
pt_hist2.fill(pt=100*np.random.rand(1000))
pt_hist3.fill(pt=100*np.random.rand(1000))

ax = plot1d(pt_hist1)
plot1d(pt_hist2,binwnorm=1,ax=ax, clear=False)
plot1d(pt_hist3,binwnorm=0.5,ax=ax, clear=False)

ax.figure.savefig("test.pdf")
```

**Expected behavior**
The comment in `plot1d` says:
```
        binwnorm : float, optional
            If true, convert sum weights to bin-width-normalized, with unit equal to supplied value (usually you want to specify 1.)
```

In the specific case here, I expected the `binwnorm` argument to 

a) result in the bin contents being plotted divided by the width of the bin. In the example above, there are 10 bins, and each histogram is filled with 1k random numbers, so the average bin yield is 1k/10=100. Therefore, with `binwnorm=1`, I'd expect the bins to be plotted with contents of yield / width ~ 100 / 10 ~ 10. However, instead I get contents around 100.

b) change the overall normalization if different values are set. I.e. if I set `binwnorm=0.5`, I'd expect to get plotted bin contents of 0.5*100, but instead I still get 100.

**Output**

![image](https://user-images.githubusercontent.com/9568102/78267043-85820180-74d4-11ea-8624-89be4a407902.png)

**Desktop (please complete the following information):**
coffea             0.6.36
mplhep             0.1.12

**Additional context**
I think this may be a problem with either mplhep itself or the way mplhep is called from coffea, but I don't know how to write minimal examples for mplhep, so I'm reporting here. @andrzejnovak

**Comment by andrzejnovak** [comment]
@AndreasAlbert  Will take a look
