### ISSUE TITLE
"binwnorm" argument to plot1d does not interact correctly with overlay/stack plots

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/coffea#291]
**Describe the bug**
I'm trying to make a typical data/MC comparison plot: MC is a stacked overlay plot, data is plotted on top as an additional overlay. Observations: When using `binwnorm=1`, the data/mc ratio shows up differently than when using `binwnorm=None`.

I think the issue may be related to how the stacked plots are normalized. The normalization seems fine for the non-stacked data histogram.

**To Reproduce**
```python
from coffea.hist import Hist, Bin, plot1d,Cat
import numpy as np

# Just aesthetics
err_opts = {
    'linestyle':'none',
    'marker': '.',
    'markersize': 10.,
    'color':'k',
    'elinewidth': 1,
}

# Want to test stack plots,
# so we need an x axis and a category
xax = Bin("x","x",5,0,10)
cat = Cat("cat","cat")

h1 = Hist("h1",xax,cat)
h2 = Hist("h2",xax,cat)

# Same random numbers will be filled into
# all histograms
rand = 10*np.random.rand(1000)

# Histogram 1 has two categories, 
# each filled with rand
# Stacked yield = 2 * rand
# (This is "MC")
h1.fill(x=rand, cat="cat1")
h1.fill(x=rand, cat="cat2")

# Histogram 2 just has one category
# fill it with higher weight to get a norm. diff
# Yield = 2.5 * rand
# (This is "data")
h2.fill(x=rand, cat="cat3",weight=2.5)


# Case 1: Plot with binwnorm = None
ax = plot1d(h1, overlay="cat", stack=True, binwnorm=None)
plot1d(h2,binwnorm=None,ax=ax, clear=False, overlay="cat",     error_opts=err_opts)
ax.set_title("binwnorm = None")
ax.figure.savefig("test_nobinw.pdf")

# Case 2: Plot with binwnorm = 1
ax.figure.clf()
ax = plot1d(h1, overlay="cat", stack=True, binwnorm=1)
plot1d(h2,binwnorm=1,ax=ax, clear=False, overlay="cat",     error_opts=err_opts)
ax.set_title("binwnorm = 1")
ax.figure.savefig("test_binw1.pdf")
```

**Expected behavior**
I expected both histograms to be divided by the same bin width, thereby conserving their ratio.

**Output**

![image](https://user-images.githubusercontent.com/9568102/78368616-e0c5f980-7591-11ea-9581-a4785bd5caf6.png)
![image](https://user-images.githubusercontent.com/9568102/78368624-e6bbda80-7591-11ea-82a7-2fe1f597276f.png)

**Desktop (please complete the following information):**
coffea             0.6.37
mplhep             0.1.13

**Additional context**
Related to #288  @andrzejnovak

**Comment by andrzejnovak** [comment]
The densitymode="stack" or sth like that. I'll reply more extensively in a
bit.

**Comment by AndreasAlbert** [comment]
Thanks for the suggestion! If I understand correctly, you are saying I should pass `densitymode="stack"` to the `plot1d` call for the stack plot? I.e. same code as before, but:
```python
# Case 2: Plot with binwnorm = 1
ax.figure.clf()
ax = plot1d(h1, overlay="cat", stack=True, binwnorm=1, densitymode="stack")
plot1d(h2,binwnorm=1,ax=ax, clear=False, overlay="cat", error_opts=err_opts)
ax.set_title("binwnorm = 1, densitymode = 'stack'")
```

If that is what you are suggesting, then it does not seem to change the behavior here:

![image](https://user-images.githubusercontent.com/9568102/78376647-9a29cc80-759c-11ea-93c3-54112bfcf445.png)
![image](https://user-images.githubusercontent.com/9568102/78376660-9eee8080-759c-11ea-8247-d10cc31ee64e.png)

**Comment by andrzejnovak** [comment]
Ah found the culprit - https://github.com/scikit-hep/mplhep/blob/master/mplhep/plot.py#L201
Thanks for pointing it out. I'll push a fix asap.

**Comment by AndreasAlbert** [comment]
With your fix in https://github.com/scikit-hep/mplhep/pull/113, it seems to work now. `densitymode` is not needed either way, right?

**Comment by andrzejnovak** [comment]
No. It's no interacting with `binwnorm` after all (that's a bug). I am still not 100% sure on that behaviour though. When using `density` it governs whether you normalize first and stack after or stack first and normalize then. But now I wonder whether there is even a use case for the former.

**Comment by AndreasAlbert** [comment]
Agree, hard to imagine a case where normalizing to unity before stacking is what you want
