### ISSUE TITLE
Mistake in formula for stochastic smearing in the JetTransformer

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#295]
**Describe the bug**
In the formula for the factor used to scale jets in order to apply the stochastic smearing according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetResolution#Smearing_procedures, one reads max(s_JET^2 - 1, 0). This is supposed to express that in case "s_JET^2 - 1" is negative, take the 0.
However in coffea's JetTransformer it reads (one of three lines where this is done) https://github.com/CoffeaTeam/coffea/blob/19efc8947c602fcb8d6ed588776d86d5514909b4/coffea/jetmet_tools/JetTransformer.py#L172
Notice the use of `np.max`. This function returns the largest element along an axis, which is specified to be `0` here. I highly doubt that is what the author intended and instead the function `np.maximum` was supposed to be used, which returns the element-wise maximum, meaning it would put a zero for every negative element inside the vector.

**Comment by lgray** [comment]
@jrueb Good catch. Thanks for finding this.
