### ISSUE TITLE
RecursionError when copying LazyDataFrame

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#299]
**Describe the bug**
When one tries to create a shallow copy a `coffea.processor.LazyDataFrame` with Python's standard `copy.copy` one gets a RecursionError.

**To Reproduce**
```
import uproot
import coffea
import copy
f = uproot.recreate("/tmp/roottest.root")
f["t"] = uproot.newtree({"branch": "int32"})
df = coffea.processor.LazyDataFrame(f["t"])
copy.copy(df)
```

**Additional context**
One can more directly trigger the error by
```
coffea.processor.LazyDataFrame.__new__(coffea.processor.LazyDataFrame).something
```
 `copy` seems to be calling the built-in `__new__` for `LazyDataFrame` which creates an instance without calling `__init__`. The error then seems to be happening because `LazyDataFrame.__getattr__` forwards to `LazyDataFrame.__getitem__`, which in turn needs attributes such as `_dict`, which causes another `__getattr__` call.
Maybe it would be better to have `__getitem__` forward to `__getattr__` as latter is more fundamental. Although preferably I think there should only be one way (see the Zen of Python) to access the items of a `LazyDataFrame`, thus getting rid of the `LazyDataFrame.__getattr__` definition altogether would solve everything.

**Comment by lgray** [comment]
Hmm, why are you making a shallow copy of a dataframe in the first place?

Need to understand use case to determine correct path forward!

**Comment by nsmith-** [comment]
Thanks for making the concise reproducible example.
Indeed I was initially opposed to having getattr and getitem accessors, but it is such a popular request that we could not avoid it. Messing with attribute access tends to be fragile, and looks like you hit one more corner case. The good news is that `__getattr__` is lowest precedence in the attribute accessor resolution, so I've made it raise `AttributeError` on any leading-underscore attributes.

**Comment by jrueb** [comment]
@lgray What I actually was fiddling with when I stumbled across this, was a shallow copy that has its `_dict` also copied like this:
```
df_copy = copy.copy(df)
df_copy._dict = copy.copy(df._dict)
```
If I wasn't violating encapsulation here, it would enable me to have two dataframes, e.g. one for up variation and one for down variation, while being memory efficient in that already-read columns are in memory only once.

**Comment by nsmith-** [comment]
Note, having getitem call getattr would not avoid this recursion error, rather getattr would recurse on itself trying to access `_dict`.

**Comment by lgray** [comment]
@jrueb Thanks for fiddling, I'll add it as a test. :-)

OK - I think the best solution is to modify the `__copy__` and `__deepcopy__` of DataFrame to match expected behaviors but deal with our `__getattr__`/`__getitem__`/`__dict__` silliness.
`
@nsmith- ok with you, or do you have a better solution in mind?

**Comment by nsmith-** [comment]
@lgray see #300
