### ISSUE TITLE
IndexedMaskedArray instead of JaggedArray

### ISSUE THREAD

**Issue by mondalspandan** [scikit-hep/coffea#307]
**Describe the bug**
I am using NanoEvents to manually match gen particles to reco particles. It seems in some cases where I expect a JaggedArray, I see an IndexedMaskedArray instead. The IndexedMaskedArrays, in turn, cannot be used as indices in a later step.

**To Reproduce**
```
from coffea.nanoaod import NanoEvents as Events
events = Events.from_file(fname)
ev = events[events.GenPart[abs(events.GenPart.distinctParent.pdgId)==13].counts > 0]

dR = ev.GenPart[abs(ev.GenPart.distinctParent.pdgId)==13][:,0].delta_r(ev.Jet)
#<JaggedArray [[0.1514539 3.2175906 3.4679737] [2.820771 0.033286493 1.9097561 2.2314553 2.9429927 2.7656577] [3.5224686 0.088498875 2.4204075 ... 5.543641 2.5681756 5.636672] ... [1.6113669 2.32577 0.02221009 ... 3.236095 4.6131806 5.4562025] [3.137512 0.022039017 3.1051576] [3.0514317 0.0427701 3.2626202 2.6618097]] at 0x7f95a91dd940>
dR = ev.GenPart[abs(ev.GenPart.distinctParent.pdgId)==13].distinctParent[:,0].delta_r(ev.Jet)
# <IndexedMaskedArray [[0.013672965 3.2105224 3.5351236] [2.835745 0.039617788 1.8842902 2.2615998 2.9058156 2.792683] [3.5373533 0.04292989 2.350842 ... 5.517534 2.618448 5.598956] ... [1.608257 2.3349986 0.008126619 ... 3.222863 4.626683 5.469888] [3.1462464 0.02658892 3.1003625] [3.077167 0.013251799 3.2324839 2.6831245]] at 0x7f95a91a6978>
```

**Expected behavior**
I would expect both to return the same datatype as the part without `delta_r` is a GenParticleArray in both cases.

The issue with the Masked Array is that I cannot use it, for example, in the following way:
`ev.Jet[dR < 0.4]` works for the first case, but returns 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`
for the second case.

**Comment by nsmith-** [comment]
I think this is an issue with awkward0. The `IndexedMaskedArray` type should be able to be used as an index, especially in this case when there are no masked entries (ensured by your previous cuts). A workaround in this context is to instead use `ev.Jet[dR.content < 0.4]`. I expect the basic issue to go away with a move to awkward1, but will leave it open to be sure.
