### ISSUE TITLE
Fix docs for `candidatesfrom<counts/offsets>

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#310]
Docstring is pretty much the same for [candidatesfromcounts](https://github.com/CoffeaTeam/coffea/blob/1dfd5ee0531914b069834a45c50a285572557efc/coffea/analysis_objects/JaggedCandidateMethods.py#L101) and [candidatesfromoffsets](https://github.com/CoffeaTeam/coffea/blob/1dfd5ee0531914b069834a45c50a285572557efc/coffea/analysis_objects/JaggedCandidateMethods.py#L132).

Should be fixed, especially since it doesn't look `candidatesfromoffsets` is made for public use.

**Comment by lgray** [comment]
Fixed in #316 to some extent. They're still largely the same since they do the same thing, but maybe there's something more you want added?
