### ISSUE TITLE
AttributeError when creating a JaggedCandidateArray from p4 in conjunction with from_ptetaphim

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#315]
**Describe the bug**
An `AttributeError` is raised when creating a `JaggedCandidateArray` from Lorentz vectors using the parameter `p4`, if the Lorentz vectors were created with `from_ptetaphim`.

**To Reproduce**
```
import numpy as np
import coffea
import uproot_methods
p4 = uproot_methods.TLorentzVectorArray.from_ptetaphim(np.array([0.]), np.array([0.]), np.array([0.]), np.array([0.]))
coffea.analysis_objects.JaggedCandidateArray.candidatesfromcounts(np.array([1]), p4=p4)
```

There is an `isinstance` call  in `candidatesfromoffsets` that only checks for `uproot_methods.TLorentzVectorArray` and not for `uproot_methods.classes.TLorentzVector.PtEtaPhiMassLorentzVectorArray`. I guess that is the cause.

**Comment by lgray** [comment]
Indeed - I'll fix that momentarily. Thanks!

**Comment by jrueb** [comment]
I just noticed in the documentation it says that `p4` is supposed to be Cartesian. So maybe this is intended. However I don't see why one would need this requirement.

**Comment by lgray** [comment]
That's for when you provide something that's not an ArrayMethods-based class.
I'll fix the docs too - thanks.
