### ISSUE TITLE
Ability to resume an uproot job

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#317]
**Is your feature request related to a problem? Please describe.**
I'm normally using `run_uproot_job` together with parsl and HTCondor. In case of a large number of chunks it happens very often to me that `run_uproot_job` does not finish. It gets stuck at the last few chunks, maybe due to hardware trouble, or there has been some other (outside of python) error. In the classic workflow without coffea and parsl, one would probably have some bash script that checks the output and resubmits missing chunks. However, with coffea this situation unfortunately means that one has to start the processing from the very beginning, any progress that has been made is lost.
I think this is a big drawback for coffea, as it makes it very unreliable for anything that takes more than just a few minutes.

**Describe the solution you'd like**
It would be nice, if `run_uproot_job` saved its state of some sort and, in case of trouble or an unforeseen crash, one can restart using this state, skipping over at least most of what has already been processed.

**Comment by andrzejnovak** [comment]
@jrueb I had this problem with parsl/slurm. Updating parsl helped - it was very unclear where the problem was.

Would you mind sharing your condor setup (barebones versions)? There's no official example and I didn't have the time to figure it out myself.

**Comment by lgray** [comment]
Now tracked in a more combined issue.
