### ISSUE TITLE
Cannot disable Dask retries

### ISSUE THREAD

**Issue by bbockelm** [scikit-hep/coffea#318]
When invoke `run_uproot_job`, the method mutates the provided dictionary (surprisingly changing things for the user if they re-run the job twice with the same dictionary).

One result of this is that disabling Dask retries are not possible.  We remove the `retries` parameter from the executor arguments:

https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L978

But that is also referred to by the Dask executor!  Hence, we can't remove retries in the documented manner.

@nsmith- did provide a workaround:

```python
executor = partial(processor.dask_executor, retries=0)
```

But this, obviously, is a bit clumsy

**Comment by lgray** [comment]
@nsmith- can you get this one?
