### ISSUE TITLE
FactorizedJetCorrector incorrectly handles JaggedArrays

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#320]
**Describe the bug**
The `getSubCorrections` and subsequently the `getCorrection` methods of `FactorizedJetCorrector` incorrectly handle JaggedAttays. It modifies the content of the inputs and raises an error when using a starts-stops JaggedArray.

**To Reproduce**
```
import awkward
import coffea
extract = coffea.lookup_tools.extractor()
extract.add_weight_sets(['* * tests/samples/Summer16_23Sep2016V3_MC_L2Relative_AK4PFPuppi.jec.txt.gz'])
extract.finalize()
evaluator = extract.make_evaluator()
corrector = coffea.jetmet_tools.FactorizedJetCorrector(**evaluator)
eta = awkward.JaggedArray.fromcounts([1, 1], [0., 0.])
rho = awkward.JaggedArray.fromcounts([1, 1], [30., 30.])
pt = awkward.JaggedArray.fromcounts([1, 1], [100., 100.])
area = awkward.JaggedArray.fromcounts([1, 1], [0.5, 0.5])
corrector.getCorrection(JetPt=pt, JetEta=eta, JetA=area, Rho=rho)
print(pt)
```
`pt` will surprisingly be changed by the `getCorrection` call and will be around 109 now.
On top of that with a starts-stops JaggedArray:
```
pt = awkward.JaggedArray([2, 3], [3, 4], [float("nan"), float("nan"), 100., 100.])
corrector.getCorrection(JetPt=pt, JetEta=eta, JetA=area, Rho=rho)
```
one will get a `ValueError`.

**Comment by lgray** [comment]
Thanks for the reproducers, I'll try to fix it soon.

**Comment by jrueb** [comment]
I can make a pull request for this, if you don't mind.
