### ISSUE TITLE
MET pT and phi not recomputed correctly in JetTransformer

### ISSUE THREAD

**Issue by jdulemba** [scikit-hep/coffea#322]
**Describe the bug**
The corrections applied to jets that modify the jet p4 via the transform method aren't propagated to the MET. Even though 'new_x' and 'new_y' are computed in lines 226-227 for the MET px and py, the resulting MET p4 remains unchanged.

**To Reproduce**
from coffea.lookup_tools import extractor
from coffea.jetmet_tools import FactorizedJetCorrector, JetCorrectionUncertainty, JetTransformer, JetResolution, JetResolutionScaleFactor
from coffea.analysis_objects import JaggedCandidateArray
import numpy as np

Jetext = extractor()
Jetext.add_weight_sets(['* * Summer16_07Aug2017_V11_MC_L1FastJet_AK4PFchs.jec.txt'])
Jetext.add_weight_sets(['* * Summer16_07Aug2017_V11_MC_L2Relative_AK4PFchs.jec.txt'])
Jetext.add_weight_sets(['* * Summer16_07Aug2017_V11_MC_L3Absolute_AK4PFchs.jec.txt'])
Jetext.add_weight_sets(['* * Summer16_07Aug2017_V11_MC_Uncertainty_AK4PFchs.junc.txt'])
Jetext.add_weight_sets(['* * Summer16_25nsV1_MC_PtResolution_AK4PFchs.jr.txt'])
Jetext.add_weight_sets(['* * Summer16_25nsV1_MC_SF_AK4PFchs.jersf.txt'])
Jetext.finalize()
Jetevaluator = Jetext.make_evaluator()

JECcorrector = FactorizedJetCorrector(**{name: Jetevaluator[name] for name in ['Summer16_07Aug2017_V11_MC_%s_AK4PFchs' % level for level in ['L1FastJet', 'L2Relative', 'L3Absolute']]})
JECuncertainties = JetCorrectionUncertainty(**{'Summer16_07Aug2017_V11_MC_Uncertainty_AK4PFchs':Jetevaluator['Summer16_07Aug2017_V11_MC_Uncertainty_AK4PFchs']})
JER = JetResolution(**{'Summer16_25nsV1_MC_PtResolution_AK4PFchs':Jetevaluator['Summer16_25nsV1_MC_PtResolution_AK4PFchs']})
JERsf = JetResolutionScaleFactor(**{'Summer16_25nsV1_MC_SF_AK4PFchs':Jetevaluator['Summer16_25nsV1_MC_SF_AK4PFchs']})
Jet_transformer = JetTransformer(jec=JECcorrector, junc=JECuncertainties, jer=JER, jersf=JERsf)

jets = JaggedCandidateArray.candidatesfromcounts(counts=np.array([2]), pt=np.array([163.375, 145.]), eta=np.array([-0.8979492 , -0.73913574]), phi=np.array([ 1.4580078, -1.4304199]), mass=np.array([32., 18.96875]), ptRaw=np.array([153.48315 , 138.60864]), massRaw=np.array([30.0625   , 18.070328]), ptGenJet=np.array([170.93062 , 151.82611]), area=np.array([0.5786133 , 0.50878906]), rho=np.array([11.517247, 11.517247]))
met = JaggedCandidateArray.candidatesfromcounts(counts=np.array([1]), pt=np.array([10.847509]), eta=0, phi=np.array([-3.055664]), mass=0)
print('Original jet pT:', jets.pt)
print('Original met pT:', met.pt)
print('Original met phi:', met.phi)

Jet_transformer.transform(jets, met)
print('\nCorrected jet pT:', jets.pt)
print('Corrected met pT:', met.pt)
print('Corrected met phi:', met.phi)

**Expected behavior**
Since the difference in the initial jet px and py and corrected jet px and py is nonzero, 'new_x' and 'new_y' should also be nonzero resulting in a change in the MET pT and phi.

**Output**
Original jet pT: [[163.375 145.0]]
Original met pT: [[10.847509]]
Original met phi: [[-3.055664]]

Corrected jet pT: [[162.27144980511775 144.30109191735738]]
Corrected met pT: [[10.847509]]
Corrected met phi: [[-3.055664]]

**Desktop (please complete the following information):**
 - python version 3.7.6 from /cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc8-opt/setup.sh
 - coffea version 0.6.38

**Comment by lgray** [comment]
@jdulemba This is fixed in the new CorrectedJetFactory and CorrectedMETFactory. These require updating to awkward 1.0 but are significantly better implementations.

The JetTransformer is deprecated so we're not gonna fix this.
