### ISSUE TITLE
Supplement `hist.integrate` with `hist.cut` which would not sum the axis out after.

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#323]
Alternatively, `hist.integrate` could take a kwarg to only apply the cut, but not sum-out the axis.

**Comment by nsmith-** [comment]
The slicing syntax should support such an operation, e.g. `h[3:10]` if the first axis has bins in range including 3-10. That said, it requires some work to input the empty slices to get to the right axis so a convenience function with axis name would be good.

**Comment by andrzejnovak** [comment]
I am not sure what the correct API is. I feel like `integrate(..., consume=False)` would be the most natural way to extend it, but that would be in semantic conflict with the meaning of "integrating out" the axis.
