### ISSUE TITLE
Allow initialization of JetTransformer without JEC specified (only with JER)

### ISSUE THREAD

**Issue by kondratyevd** [scikit-hep/coffea#327]
There are cases where one only wants to apply JER, without (re)applying JEC (for example, when computing JER systematics). Please correct me if I'm wrong, but it seems that JetTransformer would work fine without the requirement to specify JEC [1], as long as JER has been specified.

[1] [https://github.com/CoffeaTeam/coffea/blob/master/coffea/jetmet_tools/JetTransformer.py#L79-L80](https://github.com/CoffeaTeam/coffea/blob/master/coffea/jetmet_tools/JetTransformer.py#L79-L80)

**Comment by kondratyevd** [comment]
@lgray the new implementation via `JECStack` (https://github.com/CoffeaTeam/coffea/pull/364) fails for DATA when I try to build `name_map`. 
In this case the opposite happens – for DATA, JEC is specified and JER is unspecified. 

I believe a check similar to the one quoted below for `self._jer` and `self._jersf` would fix it.
And I guess the same for `self._junc` will not hurt.

https://github.com/CoffeaTeam/coffea/blob/dad1bef01ace3228403306a23ac198c58aa99229/coffea/jetmet_tools/JECStack.py#L91-L93

**Comment by lgray** [comment]
Wontfix + close due to new interfaces.
