### ISSUE TITLE
Histogram Axis <Bin> has no interval that fully contains identifier <Interval>

### ISSUE THREAD

**Issue by jdulemba** [scikit-hep/coffea#336]
**Describe the bug**
Using coffea version 0.6.38 I am unable to rebin a histogram whose original bin edges are shown in [1] and whose new bin edges are shown in [2]. The  error I get is shown in [3]. I've gotten around this problem in the past by increasing the number of bins, but when I use this binning in a 2D histogram I want to be as efficient as possible.

1. [0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]
2. [0.0, 0.4, 0.6, 0.75, 0.9, 1.0]
3.
  File "/afs/cern.ch/work/j/jdulemba/NanoAOD_Analyses/coffea/coffea/hist/hist_tools.py", line 1187, in rebin
    binmap = [new_axis.index(i) for i in old_axis.identifiers(overflow='allnan')]
  File "/afs/cern.ch/work/j/jdulemba/NanoAOD_Analyses/coffea/coffea/hist/hist_tools.py", line 1187, in <listcomp>
    binmap = [new_axis.index(i) for i in old_axis.identifiers(overflow='allnan')]
  File "/afs/cern.ch/work/j/jdulemba/NanoAOD_Analyses/coffea/coffea/hist/hist_tools.py", line 520, in index
    raise ValueError("Axis %r has no interval that fully contains identifier %r" % (self, identifier))
ValueError: Axis <Bin (name=x) instance at 0x7f81051a0e50> has no interval that fully contains identifier <Interval ([0.55, 0.6)) instance at 0x7f80d85872d0>

**To Reproduce**
from coffea import hist
import numpy as np
histo = hist.Hist('Events', hist.Bin("x", "x", 20, 0., 1.))
x_rebinning = np.array([0.0, 0.4, 0.6, 0.75, 0.9, 1.0])
histo = histo.rebin('x', hist.Bin('x', 'x', x_rebinning))

**Comment by nsmith-** [comment]
This is a floating-point issue. For example,
```
>>> any(np.linspace(0, 1, 21) == 0.6)
False
```
none of the bin edges match up because of how the first histogram is constructed. One option is to specify the binning ahead of time in the same manner as you declare `x_rebinning` to ensure it is the same exact floating-point value, e.g.
```
>>> histo = hist.Hist('Events', hist.Bin("x", "x", np.array([0.0, 0.1, 0.2, 0.3, 0.4, 0.6, 0.75, 0.9, 1.0])))
>>> histo = histo.rebin('x', hist.Bin('x', 'x', x_rebinning))
```
another option is to select the subset of bin boundaries from the original histogram:
```
>>> x_rebinning_exact = histo.axis('x').edges()[[0,8,12,15,18,20]]
>>> histo = histo.rebin('x', hist.Bin('x', 'x', x_rebinning_exact))
>>> x_rebinning_exact - x_rebinning
array([0.00000000e+00, 0.00000000e+00, 1.11022302e-16, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])
```

**Comment by nsmith-** [comment]
Let me know if the explanation is clear, and if so can you close the issue?

**Comment by andrzejnovak** [comment]
I see you marked this as wontfix, but thoughts on having this use some kind of `isclose` logic?

**Comment by nsmith-** [comment]
This is something we could suggest to the boost-histogram developers, but I consider coffea histograms in maintenance mode at the moment.

**Comment by jdulemba** [comment]
Sorry for the late reply, I took a long weekend. The explanation makes sense and in the end I implemented what Andrzej suggested as a sort of fix. Thanks!

**Comment by jrueb** [comment]
> This is something we could suggest to the boost-histogram developers, but I consider coffea histograms in maintenance mode at the moment.

Does this mean you do not plan to add any more features to the histograms?

**Comment by nsmith-** [comment]
The roadmap for `coffea.hist` is:

- Replace backend with boost-histogram, leaving user API the same
- Deprecate user API, pointing users to `hist` package (https://github.com/scikit-hep/hist)
- Add new features to `hist` package if warranted
