### ISSUE TITLE
How do I get the error of TH2F instead of bin content 

### ISSUE THREAD

**Issue by ramankhurana** [scikit-hep/coffea#358]
Hello 

For the case described here:
https://coffeateam.github.io/coffea/notebooks/applying_corrections.html#Opening-a-root-file-and-using-it-as-a-lookup-table

If the TH2F has error associated with it, can I read them as up and down weights somehow? Is there an option to turn this on?

**Comment by lgray** [comment]
Hi Raman,

The errors are checked for and yielded here:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/lookup_tools/root_converters.py#L24-L28

From here:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/lookup_tools/extractor.py#L88-L100

if you're using the lookup_tools.extractor class you can specify:
`* * path/to/histogram`

and so long as the variances in that histogram are filled it will fill `my_lookup` and `my_lookup_error` when rendering the corrections.

You should also be able to access the errors similar to the example (but it may not work as I do not recall if that histogram has errors):
```python
ext = extractor()
# several histograms can be imported at once using wildcards (*)
ext.add_weight_sets(["testSF2d scalefactors_Tight_Electron data/testSF2d.histo.root",
                     "testSF2dErr scalefactors_Tight_Electron_error data/testSF2d.histo.root"])
ext.finalize()

evaluator = ext.make_evaluator()

print("available evaluator keys:")
for key in evaluator.keys():
    print("\t", key)
print("testSF2d:", evaluator['testSF2dErr'])
print("type of testSF2d:", type(evaluator['testSF2dErr']))
```

**Comment by ramankhurana** [comment]
Thanks a lot Lindsey!! Nice and clean, worked like charm!!
