### ISSUE TITLE
project behavior w.r.t flow bins

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#361]
I know that hist is slated for replacement, but just to log it somewhere. I thought flow bins were kept track of, is this not the case?

![image](https://user-images.githubusercontent.com/13226500/97445249-5a0dab00-192d-11eb-8962-69390089398d.png)

**Comment by nsmith-** [comment]
I think the [project](https://coffeateam.github.io/coffea/api/coffea.hist.Hist.html#coffea.hist.Hist.project) takes `overflow`. So `h.project('x', overflow='all').values()` should probably work?

**Comment by andrzejnovak** [comment]
Ah yes, sorry. I'm getting confused between the conventions here/hist/uproot again
