### ISSUE TITLE
File-dependent processor behavior

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/coffea#369]
**Describe what you want to do**
How do I best deal with a scenario where I have some classes of files, and the processing to extract a histogram for each class differs slightly? I could write different processors for each class. Alternatively, how much does a processor know at runtime about the file it is processing? Could I use any information at runtime for file-dependent processing?

An example is processing of data events and simulated events. For simulated events, I want to fill histograms where events are weighted, and for data I want to fill every event with a weight of 1. I imagine I could use a try/except to access a branch containing weights, and fall back to a default weight of 1 if that fails. Is there a more elegant approach to this?

**Explain what documentation is missing**
Solutions to this problem may fit in the [processors notebook](https://coffeateam.github.io/coffea/notebooks/processor.html), or maybe in some more advanced documentation section. I did not see weights discussed in relation to processors, but I think dealing with weights naturally leads to the question of how to distinguish data from simulation.

**Comment by lgray** [comment]
Forwarding the answer from @andrzejnovak in slack:

Essentially, a lot of this can be solves by annotating your dataset with metadata, which can be introduced per-set-of-files.

However it looks like there's not a nice way of introducting metadata from `run_uproot_job` beyond dataset names and a few other things.... Do we need annotation more rich than that?

**Comment by alexander-held** [comment]
Thanks! I can see how to propagate custom metadata for `NanoEventsFactory.from_file`, and I guess there is no equivalent for `run_uproot_job`. I wonder whether it makes a lot of sense to add it to that though. If I wanted metadata that differs between files, I may have to split them into groups and run `run_uproot_job` multiple times, which does not seem ideal either. Maybe the easiest way is to determine in the processor itself what kind of file is present by looking at its content.

I'm curious how other people are dealing with weights that need to be read from branches for MC, but not for data. Maybe there is a nice solution already.

**Comment by andrzejnovak** [comment]
IMO the data/MC differentiation is easy enough. It's not like checking the metadata is any faster/easier than checking if a branch/field exists in the file/df/awkard. OTOH it's easy enough to imagine you'd want to do some run specific adjustments and that might not always be obvious from something automatically available like the dataset name.

**Comment by lgray** [comment]
Pretty flexible metadata annotation is now allowed in #502.
