### ISSUE TITLE
RuntmeError: undefined operation when slicing NanoEventsArray

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#372]
**Describe the bug**
Slicing after the events are masked but before the specific branch is loaded raises a RuntimeError. If the branch has been loaded, no error is raised. I am not sure however if this is rather a bug for awkward instead of coffea.

**To Reproduce**
```
import awkward1 as ak
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

fname = "https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_file(fname, schemaclass=NanoAODSchema).events()

events_cut = events[ak.num(events.Muon) == 1]
scale = events_cut["LHEScaleWeight"][:, 7]
```
The last line raises the following error:
`RuntimeError: undefined operation: VirtualArray::getitem_next(at)`

Tested in coffea 0.6.46 and awkward 0.4.4

**Comment by nsmith-** [comment]
There seems to be a missing implementation for getitem when the layout is virtual(listoffset(numpy)) for some reason. @jpivarski should I just forward this bug report to awkward?

A workaround is to force materialization, e.g. via `scale = (events_cut["LHEScaleWeight"] + 0)[:, 7]`

**Comment by jpivarski** [comment]
This operation is not supposed to be defined; it's supposed to materialize the array and pass `getitem_next` to it. This might be failing because field-slices remain unmaterialized now. I'm looking into it.

**Comment by jpivarski** [comment]
This is being deployed as [awkward1==0.4.5](https://github.com/scikit-hep/awkward-1.0/releases/tag/0.4.5).

**Comment by jrueb** [comment]
Works nicely, thanks.
