### ISSUE TITLE
A bug was found in coffea.Release v0.6.46 skipbadfiles true

### ISSUE THREAD

**Issue by scarletnorberg** [scikit-hep/coffea#375]
**Describe the bug**
When using 'skipbadfiles':True, the code will skip over the current input files. The order of the code was changed recently in order to fix a different bug: https://github.com/CoffeaTeam/coffea/commit/97f26761e0e52d023c290f811e259edab9aa14de
This in turn then lead to the logic error.

**To Reproduce**
1. Set 'skipbadfiles':True, 

**Expected behavior**
https://github.com/CoffeaTeam/coffea/compare/f663640..384cc79#diff-2d9bea3caaa598242f68714de8fce6dce0f181d8f7462800ef62b6710bced905R1077-R1081
This is the source of the problem with the TreeMaker files, but I assume it will also be a problem with other files. The logic doesn't make sense:
1. if skipbadfiles=True then check for metadata and if it doesn't exist, continue.
2. Check for metadata and if it doesn't exist, add it.
This seems backwards.

**Output**
There is no error just nothing is output.

**Desktop (please complete the following information):**
This is the test code that we have been using to test: https://gitlab.cern.ch/cms-emj/EMJAnalysis/-/blob/dev-snorberg/notebooks/Mini_MakePlots.ipynb

**Additional context**
Currently we are just going to change the true to false. This seems to be the case for all files because the testing I think by default sets it to false for skip bad files.

**Comment by nsmith-** [comment]
@andrzejnovak does this make sense to you? I think the original ordering with the addition of a check if the return value of the populate function is None is the fix.

**Comment by andrzejnovak** [comment]
I don't see a reason the conditions should be together, might help readability. 

IIRC the reason for  [97f2676](https://github.com/CoffeaTeam/coffea/commit/97f26761e0e52d023c290f811e259edab9aa14de) is that [this](https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L1079) chunk was crashing if it ran on a bad file or was causing a crash further down the line. 

I am not sure what's different about the reported case and the test introduced in [97f2676](https://github.com/CoffeaTeam/coffea/commit/97f26761e0e52d023c290f811e259edab9aa14de), which seems to have run fine.

@scarletnorberg If you can separate the logic and the test added in the linked PR doesn't crash, the issue I was seeing should not come back.

**Comment by lgray** [comment]
Did this reach any sort of resolution?
