### ISSUE TITLE
Disable cross-reference errors in NanoAODSchema

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#382]
**Is your feature request related to a problem? Please describe.**
Sometimes, due to a skim step, certain collections are dropped but not the cross-ref branches. This makes it impossible to open with NanoEvents using the default NanoAODSchema.

**Describe the solution you'd like**
Set a class member option to turn https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/schemas.py#L225 into a warning.

**Describe alternatives you've considered**
A workaround is to drop the offending cross-ref using a new schema class:
```python
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

class HackSchema(NanoAODSchema):
    def __init__(self, base_form):
        base_form["contents"].pop("Muon_fsrPhotonIdx", None)
        super().__init__(base_form)


events = NanoEventsFactory.from_file(
    "tests/samples/nano_dy.root",
    schemaclass=HackSchema,
).events()
```

@dryrun

**Comment by andrzejnovak** [comment]
be good to have things like this in "Discussions" as community support if it's not something that will get fixed soon

**Comment by nsmith-** [comment]
The fix in https://github.com/CoffeaTeam/coffea/pull/386/files#diff-2762b5d5dc6bb2519c3e0d2e366f71f1d2f896b478691f048d3560a4ce71294fR133 is missing a `continue` after the warning to skip generating the offsets
