### ISSUE TITLE
How to update a slice of NanoEvents branch (using awkward1)?

### ISSUE THREAD

**Issue by kondratyevd** [scikit-hep/coffea#384]
**Describe what you want to do**
I would like to update a branch (or create a new one), where the updated values are only assigned to a ***slice*** of the original branch. The slice is defined via a jagged boolean mask. I understand that `__setitem__` will not work in this case.

Example of what I want to achieve:

```
df.Muon.pt
>> [[20, 10], [200, 100], [100, 20]]

mask = df.Muon.pt>50

mask
>> [[False, False], [True, True], [True, False]]

df[‘Muon’, ‘pt_corr’] = df.Muon.pt
df.Muon.pt_corr[mask] = df.Muon.pt[mask]*1.1

df.Muon.pt_corr
>>  [[20, 10], [220, 110], [110, 20]]
```

**Comment by lgray** [comment]
Awkward1 doesn't allow in-place updates, so you'd have to alter your pattern a little bit.
I'd use ak.where.

```python3
pts = events.Muon.pt
events['Muon', 'pt_corr'] = ak.where(pts > 50, 1.1*pts, pts)
```

**Comment by lgray** [comment]
Closing this, reopen this if you need a different solution!
