### ISSUE TITLE
Question about an error with coffea 0.6.49

### ISSUE THREAD

**Issue by kmohrman** [scikit-hep/coffea#394]
**Describe what you want to do**
Hi @nsmith- 
I have a question about an error I am seeing with coffea 0.6.49. I've attempted to make a "minimal reproducible example," and put it in this GitHub repository [1]. I'm not sure if I'm just doing something wrong, or if this is maybe related to the coffea version? Thanks! 
[1] https://github.com/kmohrman/coffea-mre

**Comment by lgray** [comment]
So I tested this and we just don't handle weights when they're single numbers. The fix is fairly straightforward (np.atleast_1d).

I'd also note that filling histograms with single numbers is not how you'd typically be filling them when using coffea, so this is a unlikely corner case.

**Comment by lgray** [comment]
I'll make a release for this - 0.6.50 where it will be fixed.
