### ISSUE TITLE
Update matplotlib plots in place in notebooks

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#43]
@nsmith- is already working on this

**Comment by nsmith-** [comment]
This was addressed in #45 although the user code is not listed anywhere. Here's an example:
https://github.com/nsmith-/coffea/blob/bc61445fdc17843d5c3355edf54724b7e1a3c846/notebooks/zpeak.ipynb (cell 9)

**Comment by lgray** [comment]
Ah, didn't catch it. Thanks!
