### ISSUE TITLE
Attribute error when loading root file with TGraphErrors in add_weight_sets

### ISSUE THREAD

**Issue by danbarto** [scikit-hep/coffea#440]
**Describe the bug**
If the root file with scale factors contains TGraphErrors objects an Attribute error will be thrown because the object has no axes:

```
---> 22         edges = tuple(ax.edges() for ax in item.axes)
     23         if rootclass in histTypes:
     24             converted_file[(nicepath, "dense_lookup")] = item.values(), edges

AttributeError: 'Model_TGraphErrors_v3' object has no attribute 'axes'
```

This happens even if the TGraphErrors object is not used.

**To Reproduce**
```
from coffea.lookup_tools import extractor

ext = extractor()
ext.add_weight_sets(["ele_2016_loose EGamma_SF2D TnP_loose_ele_2016.root "])
```
TnP_loose_ele_2016.root  has to contain a TGraphErrors object.
EGamma_SF2D is just a usual TH2D.

**Expected behavior**
Just ignore the TGraphErrors objects.

The problem is this line:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/lookup_tools/root_converters.py#L22

Can this line just be moved after the if statement? I tested this locally, and it works fine for my use cases so far. Let me know if I should just open a PR with the fix.

**Comment by nsmith-** [comment]
I agree, it looks like we should not access these attributes before checking the type supports them. A PR would be welcome!
