### ISSUE TITLE
Extending Nanoevents vector

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#445]
(Continued from the mailing list)
The classes in `coffea.nanoevents.methods.vector` are still missing some common functions. What I have in mind here

- Subtractions, just like there is addition for two vector objects
- Division with numbers, just like there is multiplication
- Dot product
- `ThreeVector.cross`, returning the cross product with another `ThreeVector`
- `TwoVector.unit` and `ThreeVector.unit`, returning the corresponding unit
vector
- `LorentzVector.p3`, returning the corresponding momentum `ThreeVector`
- `LorentzVector.boostp3`, like `p3` but divided by the energy so that it
can be used for boosting
- `LorentzVector.boost`, returning the Lorentz boost using a `ThreeVector`

The naming here agrees with what is used in `uproot3_methods`. Besides `dot`, I can not find these in scikit-hep/vector. On the other hand one might argue that `p3` is too ambiguous as there already is `p2`, which is something different.

Note that `LorentzVector.boostp3` does what `TLorentzVector::BoostVector` in ROOT does, which is `LorentzVector.p3 / LorentzVector.t` and thus not equivalent to `LorentzVector.p3.unit`, which is `LorentzVector.p3 / LorentzVector.rho`.

**Comment by nsmith-** [comment]
Proposals for `LorentzVector.p3` replacement: `vecp` or `pvec` or `momentum`

**Comment by lgray** [comment]
`spacelike` is more general terminology would prefer that sort of direction
and
`myvector.spacelike` doesn't take too much to type.

**Comment by nsmith-** [comment]
Isn't `spacelike` already taken as a boolean to indicate whether `mass2 < 0` ?
Also, inviting @henryiii to the discussion

**Comment by lgray** [comment]
Ah yeah there's an unfortunate convergence of slightly different, but related, concepts in the same words.

Could also do `spatial` and `temporal`.

**Comment by jrueb** [comment]
There don't seem to be unit tests for the vectors yet. I will also add some tests for this.
