### ISSUE TITLE
dask executor should not use scatter

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#465]
The problem is that it has a 10s timeout to find workers and isn't really designed for adaptive deployments since it won't find a worker. See https://github.com/dask/distributed/issues/2454
One workaround is to always use a minimum worker count in adaptive deployment, but this is not ideal.

**Comment by nsmith-** [comment]
Also this may be the reason the scheduler dashboard crashes when looking at the task graph. See https://github.com/dask/dask/issues/5503 for that long-standing issue

**Comment by oshadura** [comment]
I will recheck if we see the same problems on coffea-casa

**Comment by nsmith-** [comment]
Fixed in #476
