### ISSUE TITLE
ak.where() in Rochester lookup crashes for arbitrary input files

### ISSUE THREAD

**Issue by kondratyevd** [scikit-hep/coffea#466]
**Describe the bug**
Rochester correction crashes for some (seemingly random) files in the dataset. 
The error log (see below) directs to `ValueError: in ListOffsetArray64` error raised by `awkward`, and in Coffea it originates from this line: https://github.com/CoffeaTeam/coffea/blob/72f0bf0cc8f54710d2c9985aae18c1b697b72bd7/coffea/lookup_tools/rochester_lookup.py#L246

If a file (2M events) is split into chunks (100k events each), the problem appears only for one of the chunks.

**To Reproduce**
This example reproduces the problem for me. The input file can be accessed via XrootD.
The Rochester correction file here is taken from Coffea tests directory.
```python
from coffea import lookup_tools
from coffea.nanoevents import NanoEventsFactory
import awkward as ak
import numpy as np

file = "root://xrootd.rcac.purdue.edu//store/mc/RunIISummer16NanoAODv6/DYJetsToLL_M-105To160_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8//NANOAODSIM//PUMoriond17_Nano25Oct2019_102X_mcRun2_asymptotic_v7_ext1-v1//70000//6D37B11E-A470-FE44-8D02-E4ED006C1D0E.root"
roch_file = "tests/samples/RoccoR2018.txt.gz"

rochester_data = lookup_tools.txt_converters.convert_rochester_file(roch_file, loaduncs=True)
rochester = lookup_tools.rochester_lookup.rochester_lookup(rochester_data)

events = NanoEventsFactory.from_root(file).events()

hasgen = ~np.isnan(ak.fill_none(events.Muon.matched_gen.pt, np.nan))
mc_rand = np.random.rand(*ak.to_numpy(ak.flatten(events.Muon.pt)).shape)
mc_rand = ak.unflatten(mc_rand, ak.num(hasgen))

mc_ksmear = rochester.kSmearMC(events.Muon.charge[~hasgen], events.Muon.pt[~hasgen],
                                   events.Muon.eta[~hasgen], events.Muon.phi[~hasgen],
                                   events.Muon.nTrackerLayers[~hasgen], mc_rand[~hasgen])


```

**Output**
```
  File "rochester_bug.py", line 20, in <module>
    events.Muon.nTrackerLayers[~hasgen], mc_rand[~hasgen])
  File "/home/dkondra/.local/lib/python3.7/site-packages/coffea/lookup_tools/rochester_lookup.py", line 187, in kSmearMC
    return k * self._kExtra(k * pt, eta, nl, u, s, m)
  File "/home/dkondra/.local/lib/python3.7/site-packages/coffea/lookup_tools/rochester_lookup.py", line 250, in _kExtra
    result = awkward.where(x > -1, 1.0 / (1.0 + x[x > -1]), awkward.ones_like(kpt))
  File "/home/dkondra/.local/lib/python3.7/site-packages/awkward/operations/structure.py", line 1409, in where
    [akcondition, left, right], getfunction, behavior, pass_depth=False
  File "/home/dkondra/.local/lib/python3.7/site-packages/awkward/_util.py", line 1012, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/home/dkondra/.local/lib/python3.7/site-packages/awkward/_util.py", line 772, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/home/dkondra/.local/lib/python3.7/site-packages/awkward/_util.py", line 813, in apply
    nextinputs.append(x.broadcast_tooffsets64(offsets).content)
ValueError: in ListOffsetArray64, cannot broadcast nested list
```

**Software:**
 - Coffea version: 0.7.1
 - Awkward version: 1.0.2

**Comment by jpivarski** [comment]
Since this error is saying that the shapes don't match, the first thing to check would be to see if the structures match using [ak.num](https://awkward-array.readthedocs.io/en/latest/_auto/ak.num.html) with each `axis` value ("do they all have the same number of items at the first level? at the second level? etc.).

The first red flag is that

https://github.com/CoffeaTeam/coffea/blob/72f0bf0cc8f54710d2c9985aae18c1b697b72bd7/coffea/lookup_tools/rochester_lookup.py#L246

assumes that `x` and `kpt` have the same structure at all levels—maybe they don't. Since you're just doing `ak.ones_like(kpt)`, you could as easily do `ak.ones_like(x)` to ensure that they have the same structure. Even more so, you could replace that with a simple scalar: `1`. The scalar will get broadcast to the right structure.

```python
>>> ak.where(
...     ak.Array([[True, False, True], [], [False, True]]),    # the array of booleans and the arrays
...     ak.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5]]),           # to draw from need the same structure
...     999                                                    # but a scalar gets broadcast
... )
<Array [[1.1, 999, 3.3], [], [999, 5.5]] type='3 * var * float64'>
```

**Comment by kondratyevd** [comment]
I checked that the arguments that I give to `rochester.kSmearMC()` all have consistent shapes by each axis.

I also tried `ak.ones_like(x)` and `1` instead of `ak.ones_like(kpt)`, but the behavior did not change.

@lgray are you able to reproduce this error on your side?

**Comment by nsmith-** [comment]
I can reproduce the error with awkward `1.0.2` but **not** with `1.2.0rc2`. Can you try updating awkward?

**Comment by kondratyevd** [comment]
@nsmith- Thanks for checking, but unfortunately upgrading `awkward` does not solve the problem.

Indeed, the error disappears if I use `1.2.0rc2`, *for this input file*. The same error somehow re-appears for other files!

Try this one:
```
root://xrootd.rcac.purdue.edu//store/mc/RunIISummer16NanoAODv6/DYJetsToLL_M-105To160_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8//NANOAODSIM//PUMoriond17_Nano25Oct2019_102X_mcRun2_asymptotic_v7_ext1-v1//70000//5ED73223-2755-C642-8DB8-8A4C03E83B11.root
```

**Comment by kondratyevd** [comment]
I noticed that `kSmearMCerror` causes the same error, but more consistently - for any input file.

**Comment by lgray** [comment]
@kondratyevd can you try this again with the latest awkward? There's been a bit of bug-smashing in other directions, but maybe knock-on effects?

**Comment by kondratyevd** [comment]
@lgray I have tested it with `coffea v0.7.2` and `awkward v1.2.2` - same result as before.
