### ISSUE TITLE
Dask IO workshop at the dask summit

### ISSUE THREAD

**Issue by martindurant** [scikit-hep/coffea#471]
http://summit.dask.org/

I am organising an IO workshop at the Dask Distributed Summit. Would someone here be interested in talking about physics and nested data processing with Dask? Particularly we like to see a range of use cases and workflows, and would particularly like to see new and diverse set of faces. You are welcome to simply submit talk proposals, or ping me directly if you would like to participate in the workshop.

**Comment by nsmith-** [comment]
Hi @martindurant in fact I have a tab open to submit an abstract since some time, and am definitely taking advantage of the fact the deadline was extended by a week :)

**Comment by martindurant** [comment]
You are not alone :)

**Comment by lukasheinrich** [comment]
where do I find this submission form? ;)

**Comment by martindurant** [comment]
https://summit.dask.org/present/ for writing a standard talk proposal. I will, together with the programme committee, sort these into workshops (and I'll submit the workshop proposal myself). Since workshops are less formal than the main programme, we can make space for demos, dev snapshots, discussion, etc., and we can also add content after the deadline if need be.

**Comment by nsmith-** [comment]
I have submitted! "Analyzing particle physics data in the scientific python ecosystem"

**Comment by martindurant** [comment]
Thanks!

**Comment by oshadura** [comment]
At the last moment, we submitted a short abstract about our experience using Dask in a high-energy physics analysis facility (combining multiple ways of launching resources, e.g. Dask Labextention and network connectivity challenges for Dask workers): "Challenges Designing Interactive Analysis Facilities with Dask". We hope it could be something interesting for the community.
