### ISSUE TITLE
skyhook CI occasionally segfaults

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#473]
See e.g. one of the recent daily CI runs:
https://github.com/CoffeaTeam/coffea/runs/2162133600?check_suite_focus=true#step:3:1989
@JayjeetAtGithub

**Comment by JayjeetAtGithub** [comment]
@nsmith- I see. Will try fixing it soon.

**Comment by JayjeetAtGithub** [comment]
#482

**Comment by JayjeetAtGithub** [comment]
@lgray @nsmith-  Looks like even by retrying 3 times, the OSD didn't boot in this [run](https://github.com/CoffeaTeam/coffea/runs/2256917612). So, something's wrong in the environment outside the container, probably the workspace that gets mapped into the container. Will try other solutions. Sorry for the continued trouble.

**Comment by JayjeetAtGithub** [comment]
Fixed by #532 . Trying to boot the osd repeatedly works by doing `ceph-osd || ceph-osd || ceph-osd`.
