### ISSUE TITLE
rados parquet CI job fails because of trying to compile pyarrow???

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#516]
@JayjeetAtGithub please look into this and fix it! Thanks!

**Comment by JayjeetAtGithub** [comment]
looking into it.

**Comment by lgray** [comment]
Ah - I know what it is, they released pyarrow 4.0 yesterday. Wheels were probably still building when the CI ran and we got unlucky.
Closing this.

**Comment by lgray** [comment]
Reopening this - it seems uglier than I thought. Lemme know what's up. :-) @JayjeetAtGithub

**Comment by JayjeetAtGithub** [comment]
Can you please send the link of the failed run ?

**Comment by lgray** [comment]
https://github.com/CoffeaTeam/coffea/runs/2448349673?check_suite_focus=true

**Comment by JayjeetAtGithub** [comment]
Okay

**Comment by JayjeetAtGithub** [comment]
Fixed by #532. Updating Skyhook to v0.2.0 and using the latest pip helped.
