### ISSUE TITLE
How do I disable 2020-resolver, it prevents me from installing coffea[servicex]

### ISSUE THREAD

**Issue by ivukotic** [scikit-hep/coffea#525]
it downloads all the versions trying to resolve dependency and always gets stuck here:
` Downloading lark-parser-0.6.5.tar.gz (258 kB)
     |████████████████████████████████| 258 kB 6.8 MB/s`
?

**Comment by lgray** [comment]
Isn't this an issue with pip, not coffea?

**Comment by ivukotic** [comment]
> Isn't this an issue with pip, not coffea?

I think it would be avoided if servicex and coffea would have compatible requirements on lark-parser, no?

**Comment by lgray** [comment]
Coffea does not directly depend on lark-parser, so it's in another library.

**Comment by nsmith-** [comment]
```
python -m venv test
source test/bin/activate
pip install coffea
pip list | grep lark
```
gives no results. So I think it is a servicex issue.
