### ISSUE TITLE
Regex in fileset

### ISSUE THREAD

**Issue by maxgalli** [scikit-hep/coffea#547]
Hi, I have a rather newbie question.

Let's say I have the following three files:
```
files = [
    "/remote_path/file1.root",
    "/remote_path/file2.root",
    "/remote_path/file3.root"
]
```
that I then feed to ```run_uproot_job``` in the following way:
```
fileset = {
    "Process": files
}

out = processor.run_uproot_job(
    fileset,
    treename="Events",
    processor_instance=MyProcessor(),
   ...
)
```

Assuming that I don't know the exact number of files, is there a way to do something like the following?
```
fileset = {
    "Process": "/remote_path/file*.root"
}
```

Similar to what can be done e.g. in [uproot.iterate](https://uproot.readthedocs.io/en/latest/basic.html#iterating-over-many-files).

Thanks,

Massimiliano

**Comment by nsmith-** [comment]
To do this in general would require us to implement a glob-like functionality for xrootd, which (correct me if I'm wrong) is also not available in bare uproot. If you are on a local filesystem it should be enough to do
```python
import glob

fileset = {
    "Process": glob.glob("/path/to/file*.root"),
}

**Comment by maxgalli** [comment]
Right, I didn't notice that for remote files it doesn't exist even in xrootd. Thanks!

**Comment by nsmith-** [comment]
Someday we will have this feature, though! Probably when we make an fsspec-xrootd.. which I've been saying for long enough that I should probably just go do it.

**Comment by kondratyevd** [comment]
@nsmith- @maxgalli it is possible to get the list of files via xrootd if you know the xrootd server address (e.g. `root://xrootd.rcac.purdue.edu/`) and path to dataset (e.g. `/store/mc/.../.../`). I do it as follows:
```python
import subprocess

command = f"xrdfs {server} ls -R {path} | grep '.root'"
proc = subprocess.Popen(command, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, shell=True)
result = proc.stdout.readlines()
paths = [server + r.rstrip().decode("utf-8") for r in result]
```

Also, while we're at it, it's possible to get list of files similarly from dataset name as specified in DAS (but it's slower). The only difference in the code above would be this:
```python
command = f'dasgoclient --query=="file dataset={path}"'
```

**Comment by andrzejnovak** [comment]
@kondratyevd oh that's good to know, I've been using das usually to create my path jsons but it would be nice to have the flexibility of fetching stuff by folder rather then dataset name
