### ISSUE TITLE
Uncertainties of the ratio plot (data/MC )

### ISSUE THREAD

**Issue by Ming-Yan** [scikit-hep/coffea#553]
The denominator(MC) uncertainty is the sumw2 of different MC sample for the `denom_fill_opts`
while the `error_opts` gives smaller  as demonstrated in the image below
![image](https://user-images.githubusercontent.com/20898477/125432214-01ed9353-7db0-4fe6-a9e1-29ee3bb573eb.png)
With the following option
 ```
plot.plotratio(
                                num=hflav_eta["Data"].sum("dataset").sum("flav").sum("pt").integrate("etawide",slice(etabin[i],etabin[i+1])),
                                denom=hflav_eta[notdata].sum("dataset").sum("flav").sum("pt").integrate("etawide",slice(etabin[i],etabin[i+1])),
                                ax=rax,
                                error_opts= {'linestyle': 'none','marker': '.', 'markersize': 10.,'color': 'tab:blue',  'elinewidth': 1},
                                denom_fill_opts={},
                                guide_opts={},
                                unc='num',
                                clear=False)
```
I am wondering the uncertainty of the denominator  should still be the sumw2 uncertainty of the MC sample 
https://github.com/CoffeaTeam/coffea/blob/master/coffea/hist/plot.py#L435

**Comment by nsmith-** [comment]
I'm not sure I follow, sorry. Is the issue that the size of the errorbar in the ratio plot for the orange and blue points is incorrect? By the way, I guess these are MC/Data then?

**Comment by Ming-Yan** [comment]
Yes, this is MC/Data ratio, and the question is why the error bar of orange/blue points are smaller than the gray band/

**Comment by nsmith-** [comment]
Grey band is calculated entirely from denominator, while error bar on points is numerator, at least when `num` option is requested. You can disable grey band by setting `denom_fill_opts=None` iirc.

**Comment by Ming-Yan** [comment]
Thanks for the answer, now it's clear to me.
