### ISSUE TITLE
How do I merge multiple categories as one new category in legend in histogram?

### ISSUE THREAD

**Issue by ico1036** [scikit-hep/coffea#580]
Hi, I'm making a histogram with different samples.
The information of samples is saved in 'dataset' category
ex) Egamma, SingleMuon, DoubleMuon 
```python
hsum_mupt = hist.Hist(
    "Events",
    hist.Cat("dataset", "Dataset"),
    hist.Cat("region", "region"),
    hist.Bin("mupt","Leading Muon  $P_{T}$ [GeV]", 300, 0, 600),
)
```
  
When I process the analysis script and draw the plot, I can see the different category in legends.
But I want to merge the categories as one category.
ex) "Egamma", "SingleMuon", "DoubleMuon" --> "Dataset"

I found this methods when dealing one data with multiple MCs in tutorial page.
```python
if year == "2018":
    notdata = re.compile('(?!Egamma)')
    data = 'Egamma'

hist.plot1d(
    h1[notdata].integrate('region',region),
    ax=ax,
    clear=False,
    stack=True,
#   order= order,
    fill_opts=fill_opts,
    error_opts = error_opts,
)

```
But now I have to merge multiple data as one data and multiple MCs as one MC.

Thank you in advance.

**Comment by nsmith-** [comment]
One helper function for this purpose is `Hist.group`: https://coffeateam.github.io/coffea/api/coffea.hist.Hist.html#coffea.hist.Hist.group
For example one can do
```python
h1.group(
    "dataset",
    hist.Cat("plotgroup", "plotgroup"),
    {"data": ["Egamma", "SingleMuon", "DoubleMuon"], "mc": []},
)
```
