### ISSUE TITLE
Dask executor pickling runner instance multiple times

### ISSUE THREAD

**Issue by yimuchen** [scikit-hep/coffea#618]
**Describe the bug**
When using dask executors, the runner instance is duplicated multiple times in memory, likely due to how the dask client extracts the working function. This is particularly problematic for the runner.metadata_cache, which, if duplicated multiple times, causes severe memory issues. 

**To Reproduce**
On any dask_executor initialized runner instance, 
```
runner( <large_fileset>, ... )
```
The memory can spike up very high depending on the number of files in the metadata_cache and the number of active workers. This occurs during the function 

**package versions**
 - `coffea`: 0.7.9
 - `dask.distributed`: 2021.10, 2021.11.1 

**Additional context**
If it is just the case of making the `metadata_cache` attribute invisible to the pickling step performed by dask, what we can do is something like what was suggested here[1], and overwrite the following two methods for Runner: 

[1] https://stackoverflow.com/questions/2345944/exclude-objects-field-from-pickling-in-python

```python
def __getstate__(self):
        state = self.__dict__.copy()
        state.pop('metadata_cache', None)
        return state
def __setstate__(self, state):
        self.__dict__.update(state)
```

This assumes that the `Runner.metadata_cache` should not be pickle-able anywhere, which may or may not be the case

**Comment by lgray** [comment]
@yimuchen can you see if this is fixed by #616 (try using master branch of coffea)

**Comment by yimuchen** [comment]
Yes, this seems to have fixed it, though a full test will probably need until next week when my queue penalty has gone down. Will confirm next week

**Comment by yimuchen** [comment]
I've confirmed that this PR fixes the issue that we are running into.
