### ISSUE TITLE
Convert dense_evaluated_lookup to use horner-form polynomials instead

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#62]
All b-tagging scale factors are horner-form polynomials of order six. 
Sometimes orders are just omitted.
It's faster to use numpy than the python loop that here's right now.

**Comment by lgray** [comment]
not relevant due to correctionlib and/or should be in correctionlib @nsmith-

**Comment by nsmith-** [comment]
Tracked in https://github.com/cms-nanoAOD/correctionlib/issues/174
