### ISSUE TITLE
Workqueue test failing in CI since 09 Dec 2021

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#625]
@btovar Could you please have a look at this? It looks like some configuration interface recently changed.

**Comment by btovar** [comment]
On it.

**Comment by btovar** [comment]
@lgray Our tests are working now. I think coffea CI should work now without any changes. (Our changes were pushed to the cctools conda-forge package.)

**Comment by lgray** [comment]
Looks resolved. Thanks for fixing it up!
