### ISSUE TITLE
Skyhook failing CI again.

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#641]
@JayjeetAtGithub Please take a look! Thanks!

**Comment by JayjeetAtGithub** [comment]
Hi @lgray , is this still an issue ?

**Comment by lgray** [comment]
Yes - https://github.com/CoffeaTeam/coffea/actions/runs/1850231224

**Comment by lgray** [comment]
Seems like it fixed itself....

**Comment by lgray** [comment]
@JayjeetAtGithub spoke too soon. it has come back up again in today's CI. Same error.

**Comment by lgray** [comment]
Please fix this. Thank you!

**Comment by JayjeetAtGithub** [comment]
@lgray , I finally can see the error. Looks like a transient centos repository error. Let me see if something can be done. Sorry for the delay in reply.

**Comment by lgray** [comment]
@JayjeetAtGithub no worries - thank you for looking into it! It seems to be more often failing than succeeding when it comes to the transient errors.
