### ISSUE TITLE
[Bug] Exception raising `processor_instance.process(events)` fails for custom Exception signatures

### ISSUE THREAD

**Issue by pfackeldey** [scikit-hep/coffea#649]
Dear coffea developer,

The following lines fail in case the catched Exception has a custom signature: https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L1234-L1240

This happened recently to us, where it catched a `DeserializationError` from uproot (see: https://github.com/scikit-hep/uproot4/blob/22407793f9eab02ce73d6843bb3395bedacab50b/src/uproot/deserialization.py#L322-L347)

Some time ago I have opened a PR to avoid this: https://github.com/CoffeaTeam/coffea/pull/360
However this resulted (for whatever reason, which I still do not really understand...) in the double printing of the error message: https://github.com/CoffeaTeam/coffea/issues/370 and thus the Exception handling was reverted to its old behaviour in https://github.com/CoffeaTeam/coffea/pull/439.

I think it is a bug when coffea completely hides Exceptions as the `type(e)(...)` call fails and thus does not even output the catched exception at all. On the other hand I understand that double printing of error messages is also annoying.

What do you think about this @lgray @nsmith- @andrzejnovak (tagging here the relevant people from the last issue and PR)?

Best, Peter

**Comment by pfackeldey** [comment]
Having a detailed look again into #370 the duplicated error message is not a duplicate. It comes from python's internal concurrent lib, which seem to chain the message once more in order to see full remote tracebacks: https://github.com/python/cpython/blob/3.7/Lib/concurrent/futures/process.py#L121-L138
So this is not a bug that it seems to be a duplicated error, it is standard python concurrent traceback handling. 
However, going back to chaining one needs to also change this part here: https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/executor.py#L982-L987 One needs to go through the Exception chain to check for `isinstance` and `"Auth failed" in str(e)` and not just the "head" of the Exception chain.

**Comment by nsmith-** [comment]
I wonder if this is related to the issue I've started seeing lately with the new jupyter notebook exception formatter, it seems to die on the messages we produce. (can be seen in the latest `coffea-dask` docker image e.g.)
