### ISSUE TITLE
Installing coffea and dask 

### ISSUE THREAD

**Issue by cbernet** [scikit-hep/coffea#653]
Hello and thanks a lot for your work here ! I think coffea / awkward / dask are the future :-) 

I would like to run coffea with dask. I tried to install like this: 

```
conda install -c conda-forge coffea dask-jobqueue dask jupyter
```

But environment solving takes forever. 

Could you please suggest a recipe to install these packages together ?

**Comment by andrzejnovak** [comment]
@cbernet I think these should all be pip installable as well. If you still want a conda install but faster you can install [mamba](https://mamba.readthedocs.io/en/latest/installation.html), which has a faster solver and use that instead - replacing `conda` with `mamba` in the command you link.

**Comment by lgray** [comment]
@cbernet `pip install coffea[dask]` from within a fresh conda environment works pretty well.

Otherwise - yeah use mamba (we do for our container builds).

If you'd rather just not install things at all:
```bash
singularity exec -B $(pwd):/srv -B <other> -B <bind> -B <mounts> --pwd /srv \
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest \
  /bin/bash 
```
and if you have a .rcfile you like add: `--rcfile /srv/.bashrc` to the end. You can use that container in batch jobs as well.

**Comment by cbernet** [comment]
Hello and thanks @andrzejnovak @lgray. I was able to install. 

If I may request a bit more help, could you please let me know where to find the documentation showing how to use the dask executor with a coffea processor ? 

Btw I'm using dask on a slurm cluster, with dask-jobqueue. I create my cluster like this: 

```
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(
    # queue='normal',
    project="cms",
    cores=8,
    memory="64 GB", 
    walltime="02:00:00",
)

cluster.scale(jobs=8) 
```

**Comment by lgray** [comment]
@cbernet That's a bit cluster specific but the simplest example that also uses a condor cluster (the LPC in this case) is here:
https://github.com/CoffeaTeam/lpcjobqueue/blob/main/simple_example.py

All you should need to do is replace the LPCCondorCluster with the SLURMCluster you've posted (assuming consistency of environment at the workers, etc).

**Comment by lgray** [comment]
Also - the list of files it is processing is here: https://github.com/CoffeaTeam/lpcjobqueue/blob/main/fileset.json

**Comment by lgray** [comment]
Oh - a not so minor detail - you should use `cores=1` or `cores=2` in your cluster definition. uproot/awkward do not multithread in python very well (past two threads) so every task needs to stick in its own process.

**Comment by cbernet** [comment]
Thank you very much ! it's running. cheers

**Comment by lgray** [comment]
@cbernet if you need help with anything else just ask. We have a mattermost channel in LPCPhysDiscuss.
