### ISSUE TITLE
Error propagation going wrong somewhere

### ISSUE THREAD

**Issue by sthapa** [scikit-hep/coffea#666]
**Describe the bug**
Alex Held ran into a bug where error messages aren't being properly propagated.  He queried for a non-existent column but got an error message that was not helpful.  

He got 
```
Transform 49878b73-33ea-4962-91b7-3d2256175ac9 had 1 errors:
  Error transforming file: h
```
.  Looking at the local log files, the actual error was:
```
Transform 767155f1-32fd-4e40-8d80-1a6d7cb2ecb5 had 1 errors:
Errors: {'pod-name': 'transformer-767155f1-32fd-4e40-8d80-1a6d7cb2ecb5-849899975qwnn9', 'file': 'https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root', 'events': 0, 'info': "error: Failed to transform input file https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root: not found: 'mini' (with any cycle number)\n\n    Available keys: 'events;1'\n\nin file https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root"}
  -> error: Failed to transform input file https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root: not found: 'mini' (with any cycle number)
  -> 
  ->     Available keys: 'events;1'
  -> 
  -> in file https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root
```

It looks like the uri reference in the file gets truncated to the first character (in other instances he got f as the file name, presumably from a file:// uri).

**To Reproduce**
Alex has a notebook that can reproduce this bug.  Just load the notebook up and run it.

**Comment by alexander-held** [comment]
Notebook: https://gist.github.com/alexander-held/d7ba904816a77d4dbb51c8eca41004bd

I didn't carefully track my environment setup, but I've seen this issue with the single-letter error appear and disappear a few times when testing in various different setups. I can currently reproduce it locally with Python 3.9.12,
```
coffea               0.7.14
func-adl-servicex    2.0
servicex             2.5
servicex-clients     1.2.2
servicex-databinder  0.2.6
```
and running against https://uproot-atlas.servicex.af.uchicago.edu/. I'm not 100% sure whether the issue only appears when involving `coffea` or not.

**Comment by alexander-held** [comment]
I managed to reproduce this without `coffea` as well, this may be an issue in ServiceX itself: https://github.com/ssl-hep/ServiceX/issues/408.

**Comment by alexander-held** [comment]
I think this can be closed as resolved via https://github.com/ssl-hep/ServiceX_App/pull/183.
