### ISSUE TITLE
Increasing Memory Usage With Each `processor.ProcessorABC.process`

### ISSUE THREAD

**Issue by kkrizka** [scikit-hep/coffea#669]
I noticed that my coffea processor consumes increasingly large amounts of memory when running over a large dataset. The input is a simple TTree (all branches are basic types). The memory consumption of the python process is *steadily increasing* with each iteration of `processor.ProcessorABC.process` until it is fully filled up. Naively, I would think that any memory allocated for a call (ie: all loaded events) to `process` would be freed after the call.

Is this expected?

While trying to reproduce this in a simple example, I've noticed that the problem is correlated with a larger number of baskets.

I've prepared a [demonstrative MRE in my GitHub](https://github.com/kkrizka/mre-coffea-memory). It creates a simple TTree (100M events, 10 or 10k baskets, 3 branches of floats) and then processes it in different ways.

- `utest.py` uses `uproot.iterate`
- `ftest.py` calls `NanoEventsFactory.from_root` multiple times
- `ptest.py` creates a `processor.ProcessorABC` and uses `run_uproot_job`+`iterative_executor`

The observations are:
- `utest.py` is fine. So this is not an uproot problem.
- `ftest.py` is fine. So everything is cleaned up once a file is closed.
- `ptest.py` has memory usage slowly increasing (up to 1GiB) at every call to `process`. Then it drops. [example output](https://github.com/kkrizka/mre-coffea-memory/runs/6310088177)

According the `tracemalloc`, the following package is responsible for most of it at peak:
```
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/source/file.py:67: size=858 MiB, count=30, average=28.6 MiB
```

For my actual application, the `tracemalloc` shows the following top 10 memory users. The `compression.py` is slowly growing in each call to `processor.ProcessorABC.process`.
```
[ Top 10 ]
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/compression.py:442: size=27.7 GiB, count=4335, average=6699 KiB
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/interpretation/library.py:76: size=4543 MiB, count=23804, average=195 KiB
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/coffea/nanoevents/mapping/base.py:104: size=4543 MiB, count=23804, average=195 KiB
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/coffea/hist/hist_tools.py:1082: size=2600 MiB, count=11903, average=224 KiB
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/model.py:753: size=170 MiB, count=2365002, average=75 B
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/source/cursor.py:48: size=127 MiB, count=2564484, average=52 B
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/model.py:807: size=122 MiB, count=760232, average=168 B
/global/common/software/nersc/cori-2022q1/sw/python/3.9-anaconda-2021.11/lib/python3.9/json/decoder.py:353: size=101 MiB, count=1263487, average=84 B
/global/u2/k/kkrizka/lowmu/coffea_plots/.venv/lib/python3.9/site-packages/uproot/source/cursor.py:118: size=99.0 MiB, count=1533798, average=68 B
```

This can also be reproduced by running on an CMS Open Data MiniAOD multiple times.
```
python ptest.py $(printf '/data/kkrizka/opendata/cms/Run2015D/SingleMuon/MINIAOD/16Dec2015-v1/0034202D-A3A8-E511-BA9C-00259073E3DA.root %.0s' {1..10})
```

Last being:
```
--- [ Top 5 ] --- (total: 450592678)
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/compression.py:93: size=58.8 MiB, count=18, average=3343 KiB
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/model.py:753: size=44.7 MiB, count=607619, average=77 B
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/source/cursor.py:48: size=37.1 MiB, count=748696, average=52 B
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/model.py:807: size=29.8 MiB, count=185920, average=168 B
/usr/lib/python3.9/json/decoder.py:353: size=29.0 MiB, count=362249, average=84 B
--- [ Top 5 ] --- (total: 500308957)
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/compression.py:93: size=65.3 MiB, count=20, average=3343 KiB
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/model.py:753: size=49.6 MiB, count=675133, average=77 B
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/source/cursor.py:48: size=41.3 MiB, count=831884, average=52 B
/home/kkrizka/MRE/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/model.py:807: size=33.1 MiB, count=206578, average=168 B
/usr/lib/python3.9/json/decoder.py:353: size=32.2 MiB, count=402491, average=84 B
```

For reasons I don't understand, the example ROOT files from this MRE can also use up a lot of memory in `compression.py` if you first run them through hadd (ie: `hadd example_wtf.root example_10000.root`).

**Comment by nsmith-** [comment]
This is a very thorough bug report, so thanks very much for that! I'm unfortunately unable to reproduce the problem on my machine with your demo. Rather, I see a relatively constant 100MB of rsize as the program runs, and tracemalloc only sees 30ish of that (probably the rest is the python shared libraries):
```
(.venv) [ncsmith@mac-132492 mre-coffea-memory (main)]$ python ptest.py example.root
...
--- [ Top 5 ] --- (total: 26465206)
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/source/file.py:67: size=22.9 MiB, count=8, average=2930 KiB
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/rich/_lru_cache.py:31: size=544 KiB, count=4098, average=136 B
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/rich/control.py:182: size=179 KiB, count=1525, average=120 B
<string>:3: size=144 KiB, count=2035, average=73 B
/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tracemalloc.py:67: size=75.4 KiB, count=1206, average=64 B
--- [ Top 5 ] --- (total: 32527107)
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/uproot/source/file.py:67: size=28.6 MiB, count=10, average=2930 KiB
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/rich/_lru_cache.py:31: size=544 KiB, count=4098, average=136 B
/Users/ncsmith/src/mre-coffea-memory/.venv/lib/python3.9/site-packages/rich/control.py:182: size=179 KiB, count=1525, average=120 B
<string>:3: size=144 KiB, count=2035, average=73 B
/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tracemalloc.py:67: size=76.7 KiB, count=1227, average=64 B
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1000/1000 [ 0:03:30 < 0:00:00 | 4.6 chunk/s ]
(.venv) [ncsmith@mac-132492 mre-coffea-memory (main)]$
```
Are you able to reproduce this on, e.g. lxplus or cmslpc machine? Then I might be able to look further.
Also, it might be helpful to see the exact versions of awkward and uproot you have in your environment.

**Comment by kkrizka** [comment]
Hi @nsmith-,

I do admit I am not completely happy with the example I have running in the GitHub Actions. I had a lot of trouble generating a simple input file for the example. This one came the closest, but the memory usage does reset periodically.

It is more obvious in the following examples:

```
(.venv) (base) [kkrizka@lxplus767 mre-coffea-memory]$ python ptest.py $(printf '/eos/user/k/kkrizka/public/MRE/mre-coffea-memory/0034202D-A3A8-E511-BA9C-00259073E3DA.root %.0s' {1..10}) 2> /dev/null | grep total
--- [ Top 5 ] --- (total: 57170249)
--- [ Top 5 ] --- (total: 111403724)
--- [ Top 5 ] --- (total: 165335501)
--- [ Top 5 ] --- (total: 219825484)
--- [ Top 5 ] --- (total: 274013611)
--- [ Top 5 ] --- (total: 328188539)
--- [ Top 5 ] --- (total: 382259607)
--- [ Top 5 ] --- (total: 436484099)
--- [ Top 5 ] --- (total: 490612807)
--- [ Top 5 ] --- (total: 544987604)
```

I've also copied the file I first run into this problem to eos. It has a simpler structure (all branches are basic types).
```
(.venv) (base) [kkrizka@lxplus767 mre-coffea-memory]$ python ptest.py /eos/user/k/kkrizka/public/MRE/mre-coffea-memory/input.root 2> /dev/null | grep total
--- [ Top 5 ] --- (total: 59322355)
--- [ Top 5 ] --- (total: 88101462)
--- [ Top 5 ] --- (total: 116969919)
--- [ Top 5 ] --- (total: 145732653)
--- [ Top 5 ] --- (total: 174532459)
--- [ Top 5 ] --- (total: 203331115)
--- [ Top 5 ] --- (total: 232112013)
--- [ Top 5 ] --- (total: 260910287)
--- [ Top 5 ] --- (total: 289709530)
...
--- [ Top 5 ] --- (total: 1498388732)
--- [ Top 5 ] --- (total: 1527188075)
...
```

I setup the environment as follows on lxplus:
```
python3.6 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
```

**Comment by bfis** [comment]
Just for your information, we've been using coffea with dask and have seen similar memory leaks issues in the dask workers. We've not been able to come up with any further insights since the issue seems to be very situational (i.e. it is less pronounced/absent if the same chunks are processed with the iterative executor). We'll keep you posted on any news regarding our/reproduction of your memory issues - though it may take some while.

**Comment by andrzejnovak** [comment]
@bfis Have you had a chance to look if that effect could be from output merges? I suppose running the same processor but only writing out sth like `sumw` should answer that.

**Comment by bfis** [comment]
> @bfis Have you had a chance to look if that effect could be from output merges? I suppose running the same processor but only writing out sth like `sumw` should answer that.

I'm very sure that it's not output merge related, since we explicitly force all these jobs to run on different workers (that never run the normal processing workload).

**Comment by nsmith-** [comment]
Is this possibly the same issue as #249 ?

**Comment by kkrizka** [comment]
My example is already using the `iterative_executor`. My understanding of #249 is that the memory allocation patterns don't affect this single-threaded executor drastically.

**Comment by kkrizka** [comment]
I made some progress. The issue seems to be related to the input TTree containing a type not supported by uproot (unsigned long, `/g`). I can reproduce this with a simple example input file that [contains only an unsigned long branch](https://github.com/kkrizka/mre-coffea-memory/blob/main/create_input.C).

You can see the [example grows to 50 MiB at some point](https://github.com/kkrizka/mre-coffea-memory/runs/7368699147?check_suite_focus=true):
```
--- [ Top 5 ] --- (total: 78139519)
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/compression.py:93: size=51.3 MiB, count=520, average=101 KiB
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/model.py:754: size=1905 KiB, count=25824, average=76 B
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/model.py:808: size=1553 KiB, count=9467, average=168 B
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/source/cursor.py:48: size=1523 KiB, count=29998, average=52 B
/home/runner/work/mre-coffea-memory/mre-coffea-memory/.venv/lib/python3.8/site-packages/uproot/source/cursor.py:118: size=1049 KiB, count=17103, average=63 B
```

**Comment by lgray** [comment]
That's quite weird and I think you should open an issue in uproot since it appears to be a problem there! @jpivarski

**Comment by lgray** [comment]
Thank you so much for digging into this!

**Comment by kkrizka** [comment]
I am a bit skeptical that this is an uproot problem. I have trouble reproducing it with just an `uproot.iterate`. I suspect it is a problem with how coffea uses awkward arrays. I've noticed that the problem also goes away if I disable lazy loading in [NanoEventsFactory.events()](https://github.com/CoffeaTeam/coffea/blob/b14672ef969fa0ee0e4ad150936bc6465dbde7bd/coffea/nanoevents/factory.py#L393). I'll continue digging.

**Comment by nsmith-** [comment]
Unlike for uproot.iterate, we (unfortunately) currently re-open the file with uproot per chunk. So if there is some leak in uproot on accessing such a branch, it will grow for coffea but not for uproot.iterate.

**Comment by nsmith-** [comment]
On the other hand, this code does not seem to cause any growth:
```python
import uproot
import sys
if len(sys.argv)==1:
    print('usage: {0} input.root [input.root]'.format(sys.argv[0]))
    sys.exit(0)

import tracemalloc
tracemalloc.start()

for _ in range(100):
    with uproot.open(sys.argv[1]) as fin:
        tree = fin["Events"]
        for key, branch in tree.iteritems():
            if isinstance(
                branch.interpretation,
                uproot.interpretation.identify.UnknownInterpretation,
            ):
                print(f"Skipping {key} as it is not interpretable by Uproot")

        current = tracemalloc.get_traced_memory()[0]
        snapshot = tracemalloc.take_snapshot()
        print("--- [ Top 5 ] --- (total: {})".format(current))
        for stat in snapshot.statistics('lineno')[:5]:
            print(stat)
```
So we must have some strange situation

**Comment by lgray** [comment]
@kkrizka you should check this now with awkward 1.10.3 . It is likely fixed.

**Comment by lgray** [comment]
Also not observed in awkward2 / coffea 2023. Closing this issue.
