### ISSUE TITLE
Wrong sign in ThreeVector/LorentzVector subtraction

### ISSUE THREAD

**Issue by lauridsj** [scikit-hep/coffea#674]
When using the vector mixins for Awkward Arrays, subtracting a LorentzVector from a ThreeVector gives the wrong sign in the result.

Minimal example:
```
import awkward as ak
from coffea.nanoevents.methods import vector
ak.behavior.update(vector.behavior)

vec3 = ak.zip({"x": 1., "y": 2., "z": 3.}, with_name="ThreeVector")
vec4 = ak.zip({"x": 4., "y": 5., "z": 6, "t":10}, with_name="LorentzVector")

print(vec3 - vec4) # gives (3,3,3) when it should give (-3,-3,-3)
```
Converting the LorentzVector into a ThreeVector explicitly fixes it:
```
print(vec3 - vec4.pvec) # gives (-3,-3,-3) correctly
```
The issue happens in the same way for RecordArrays of ThreeVectors / LorentzVectors. Notably, the other direction - subtracting a ThreeVector from a LorentzVector - is fine. I looked at the mixin code quickly but could not identify the source of the problem.

This is on Linux, with python 3.8.10, coffea 0.7.14 and awkward 1.7.0.

Thanks and have a nice day!

**Comment by nsmith-** [comment]
Thanks for the bug report!
Indeed it looks like the subtract mixins (e.g. https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/methods/vector.py#L151) do not disable auto-generation of transposed signature (`transpose=True` by default in https://awkward-array.readthedocs.io/en/latest/_auto/ak.mixin_class_method.html#ak.mixin_class_method)
We should set `transpose=False` for these so the non-commutativity is respected.
