### ISSUE TITLE
Possibility of skipping pre-processing

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/coffea#675]
**Is your feature request related to a problem? Please describe.**
As far as I understand, the pre-processing stage distributes the available events in all input files into units of work. In cases where the number of input files is very large, pre-processing can take a non-negligible amount of time. Particularly for cases where the number of events per file is roughly constant, and every individual file can be taken as one unit of work, it might be desirable to skip pre-processing completely.

**Describe the solution you'd like**
A possibility to skip pre-processing by declaring each input file as an individual unit of work.

**Describe alternatives you've considered**
Merging input files to speed up pre-processing.

**Additional context**
n/a

**Comment by lgray** [comment]
This is addressed and fixed in #882.
