### ISSUE TITLE
Combining friend trees in run_uproot_job? 

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#676]
I would like to be able to open friend trees in run_uproot_job. I am able to include information from fiend trees when calling my processor on an events array:
```
    event  = NanoEventsFactory.from_root(path+event_file,  schemaclass=NanoAODSchema, metadata=metadata).events()
    SvB    = NanoEventsFactory.from_root(path+SvB_file,    schemaclass=MultiClassifierSchema).events().SvB
    SvB_MA = NanoEventsFactory.from_root(path+SvB_MA_file, schemaclass=MultiClassifierSchema).events().SvB_MA
    event['SvB']    = SvB
    event['SvB_MA'] = SvB_MA
    nEvent = len(event)

    a = analysis()
    out = a.process(event)
```

Essentially I have the output from my own PyTorch classifiers stored in separate root files with their own event trees. I also have a basic little schema I wrote which makes reading these trees convenient. 

I haven't found a way to get this information in a run_uproot_job call which seems critical to being able to run condor jobs.

**Comment by lgray** [comment]
Hey! Thanks for the question! We intend to add a stable API for this in coffea 0.8, which will happen within the calendar year.

Right now there is no API for this but is is ~possible from within a processor to do this assuming you have a suitable naming scheme for pairing up your files, and reasonably static file locations for your additional inputs.

You can access the file and chunk being processed through the following private interface:
```python3
events.behavior["__events_factory__"]._partition_key
```

So long as you can reconstruct the name of your additional input file from the partition key (up and to including a large map in your processor if that's the only way) then you can open the additional file with `NanoEventsFactory.from_root` and then zip the information into the rest of your data.

It will be up to you to verify that you have zipped the correct data together.

As fair warning this is a (relatively stable) private interface and it can change, so if you're going to do this you may need to follow our developments closely.

Please let us know if you have any questions, and knowing your opinions for implementing a public interface for this would be super useful!

**Comment by patrickbryant** [comment]
Hmm I'm not sure how to use the uuid to reconstruct the file path. I thought maybe I could do something with the metadata dictionary, it would be nice if run_uproot_job added the input file path to the metadata dict.

**Comment by patrickbryant** [comment]
When I print the events.behavior["__events_factory__"]._partition_key it outputs:
```
832c6026-cfac-11ec-9280-9bcee183beef/%2FEvents%3B1/0-72592
```
Is this first part the file path uuid and the second part the ttree path or something? 
My friend tree files are in the same directory as the main events tree and have the same tree name.

**Comment by patrickbryant** [comment]
Ah I guess it does?
https://github.com/CoffeaTeam/coffea/blob/f3da7d8ee21c5916c89395a3cf4348a2c6ce8c17/coffea/processor/executor.py#L1482

Any reason I can't just use this info to grab the friend trees?

**Comment by lgray** [comment]
Ah - yes - my fault there since I was taking the example from someone trying to do skimming.
You'll need to use the metadata to get the filename of the input since you need that.

The UUID + chunk range in the `_partition_key` allows you to make consistent/reusable output file names.

In your case you need the chunk range and the input file name / location. You can take that all from the metadata in the events, which is a much more stable public interface. 

In any case you've learned how to make idempotent skims too. :-)

**Comment by patrickbryant** [comment]
Ok great thanks. 
Here's my solution:
```
        fname = event.metadata['filename']
        estart = event.metadata['entrystart']
        estop  = event.metadata['entrystop']                                                                                                                                                                                                                                            

        path = fname.replace(fname.split('/')[-1],'')
        SvB    = NanoEventsFactory.from_root(path+'SvB.root',    entry_start=estart, entry_stop=estop, schemaclass=MultiClassifierSchema).events().SvB
        SvB_MA = NanoEventsFactory.from_root(path+'SvB_MA.root', entry_start=estart, entry_stop=estop, schemaclass=MultiClassifierSchema).events().SvB_MA
        event['SvB']    = SvB
        event['SvB_MA'] = SvB_MA
```

When I was running the processor myself I was adding information to the metadata like:
```
    metadata['year'] = 2016                                                                                                                                                                                                                                                                       
    metadata['lumi'] = 36.3e3                                                                                                                                                                                                                                                                     
    metadata['xs'] = 0.03105*0.5824**2                                                                                                                                                                                                                                                            
    metadata['kFactor'] = 1                                                                                                                                                                                                                                                                       
    metadata['isMC'] = True          
``` 

I've moved these to attributes of my processor which I can specify when I make the processor_instance for run_uproot_job:
```
    analysis_args = {}
    analysis_args['isMC'] = True
    analysis_args['lumi'] = 36.3e3
    analysis_args['xs']   = 0.03105*0.5824**2
    analysis_args['year'] = 2016

    output = processor.run_uproot_job(
        fileset,
        treename='Events',
        processor_instance=analysis(**analysis_args),
        executor=processor.futures_executor,
        executor_args={"schema": NanoAODSchema, "workers": 4},
        chunksize=100000,
        maxchunks=None,
    )
```

I also find it useful to normalize the samples properly at run time rather than when plotting using the Runs TTree which has genEventSumw:
```
        if self.isMC:
            with uproot.open(fname) as rfile:
                Runs = rfile['Runs']
                genEventSumw = np.sum(Runs['genEventSumw'])
```
Any reason I shouldn't be doing this in the process function of my processor?

**Comment by andrzejnovak** [comment]
@patrickbryant you can in principle, but I would recommend storing "raw" output and scaling them after, easier to correct things later without rerunning

**Comment by lgray** [comment]
@patrickbryant you can set metadata per dataset from the fileset that you build! You can do something like:
```python3
 fileset = {
        "ZJets": {
            "treename": "Events",
            "files": [osp.abspath("tests/samples/nano_dy.root")],
            "metadata": {"somemetadata": "b tag", "isMC": True},
        },
        "Data": {
            "treename": "Events",
            "files": [osp.abspath("tests/samples/nano_dimuon.root")],
            "metadata": {"somemetadata": "a tag", "isMC": False},
        },
    }
```

i.e. you can have dictionaries additional annotations as part of your fileset!

**Comment by patrickbryant** [comment]
Oh that's awesome! Perfect

**Comment by lgray** [comment]
Reopening this so people can find it.

**Comment by lgray** [comment]
With coffea 2023 you can now get the Runs tree and do stuff with it in parallel to event-level manipulations.

You can ensure consistent processing by requesting the outputs at the same time.

```python3
runs = uproot.dask("/path/to/some/file.root:Run", open_files=False)
events = NanoEventsFactory.from_root(...)

run_stuff = process_runs(runs)
event_stuff = process_events(events)

dask.compute(run_stuff, event_stuff)
```

table joins are still a bit out, doing it well is difficult.
