### ISSUE TITLE
Picking 'random' numbers which will always be the same for a given event?

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#682]
In the c++ version of my analysis code there are a few spots where we make use of random numbers. In order to ensure the results are always the same for a given event we set the generator seed using the event number. Is there a fast/efficient way to do this with numpy arrays? Seems bad to generate the array one event at a time in a for loop.

Something like:
```
np.random.uniform(0, 1, size=len(events), seed=events.event)
```

From what I can find this functionality does not exist in numpy. Perhaps what I actually want is a hash of the event number where the hashing function samples the uniform distribution.

**Comment by andrzejnovak** [comment]
Generate a hash from filename:start:stop and use that for the seed?

**Comment by patrickbryant** [comment]
Yeah I was thinking that but I can imagine scenarios where I end up running the same file with different chunk sizes

**Comment by NJManganelli** [comment]
Perhaps the performance cost would not be too bad from using e.g. in CMs the luminosity block as the seed for the random generator and filling an array via masking/where. I don’t know if I ever checked to see if that varies in CMS MC or not, though, the lumi… run is always 1 IIRC. Anything else that might be common across 1000s of events but not dependent on chunking/skimming/etc?

Nick M

**Comment by nsmith-** [comment]
A similar issue came up with JER smearing as discussed in #454.
The approach still is chunk-splitting-sensitive. We'll need to add a feature to correctionlib to do this anyway so perhaps that can be stolen/reused: https://github.com/cms-nanoAOD/correctionlib/issues/130

**Comment by lgray** [comment]
This appears answered. Re-open if not.

**Comment by nsmith-** [comment]
Yes, correctionlib includes a facility to generate deterministic pseudorandom data. See https://cms-nanoaod.github.io/correctionlib/correctionlib_tutorial.html#Resolution-models for an example
