### ISSUE TITLE
Maxevents

### ISSUE THREAD

**Issue by slehti** [scikit-hep/coffea#683]
When developing code, I run coffea over a small number of events. I limit the number of events with Chunksize=maxevents, and Maxchunks=1. It takes about 4 secs to run the code. However, preprocessing seems to use all the data and it takes about 3 mins.
I would like to be able to limit the preprocessing to the same limited data as the processing.

Comment from Nick Smith: It used to be the case that if maxchunks was set, it would only preprocess enough files to give you the needed chunks. That has gone away but I hope it will come back in the future.

Feature request: possibility to limit the number of processed and preprocessed events to some user definable value.

**Comment by lgray** [comment]
This is fixed permanently in #882.
