### ISSUE TITLE
nanoevents uproot mapping in coffea v0.7.15 needs update for changes in uproot v4.2.4  (.awkward_form method)

### ISSUE THREAD

**Issue by btovar** [scikit-hep/coffea#686]
**Describe the bug**

As seen in uproot issue https://github.com/scikit-hep/uproot5/issues/614, the arguments of the `.awkward_form` method used in https://github.com/CoffeaTeam/coffea/blob/532c69afc8f837c6886542727d493b274d2e2c78/coffea/nanoevents/mapping/uproot.py#L94 have changed.   The method now takes a second required argument `context`. To preserve the current default behavior, this argument should be set to:

```python
{"index_format": "i64", "header": False, "tobject_header": True, "breadcrumbs": ()}
```

I have not checked if this method is used somewhere else in coffea. I can make this pr if you want.

**Comment by jpivarski** [comment]
Well, actually, that's our fault; Uproot will change back. The method didn't have a leading underscore, so it's public and we (I) shouldn't be changing the interface without warning like that.

@aryan26roy is making the `Interpretation.awkward_form` methods accept the same arguments that they used to (which then immediately create the new `context` and pass that down through a bunch of internal `awkward_form` functions, separate from the `Interpretation.awkward_form`). Coffea will not need to change.

This will be deployed as Uproot 4.3.0, first in a line of bug-fix releases for Uproot 4, tagged from the new `main-v4` branch. It will also be a test of this new v4 bug-fix workflow.

**Comment by jpivarski** [comment]
See https://github.com/scikit-hep/uproot5/issues/614#issuecomment-1162434040.
