### ISSUE TITLE
Pin some dependencies to specific versions

### ISSUE THREAD

**Issue by riga** [scikit-hep/coffea#687]
Hi!

This "issue" is something between "feature request", "bug report" and a suggestion :)

When installing coffea and its requirements, I've noticed that some version checks are rather loose, e.g. here:

https://github.com/CoffeaTeam/coffea/blob/532c69afc8f837c6886542727d493b274d2e2c78/setup.py#L60

This can cause situations where updates of upstream dependencies, that changed parts of their API, are propagated to the user. This happens, for instance, at the moment:

Signatures of some core functions in `uproot` were changed between patch releases ([from 4.2.3 to 4.2.4](https://github.com/scikit-hep/uproot5/commit/04a775267574ab1687df7a03a2bb1e2fb2790aa4#diff-bf61590d05b6dde9ae4aab8ffeccacf52c8d5379997354ebe59cca60df2d12b3R409), released yesterday), leading to

```python
TypeError: awkward_form() missing 1 required positional argument: 'context'
```

being raised here:

https://github.com/CoffeaTeam/coffea/blob/532c69afc8f837c6886542727d493b274d2e2c78/coffea/nanoevents/mapping/uproot.py#L94

It think in most situations it should be sufficient to pin dependencies to a certain minor release (e.g. `scipy==1.1.*`), or, if necessary, to patch releases for packages not strictly following semantic versioning where these API changes are known to happen from time to time (e.g. `uproot==4.2.3`). I think this would help to be more robust against breaking changes in upstream deps.

Fyi: I'm trying to create a PR in the meantime to address the above mentioned issue, but I might need some time to dive in :)

**Comment by nsmith-** [comment]
This is related to #686, and the issue was a regression in uproot. So what we should do is filter `uproot>=4.1.6,!=4.2.4`

**Comment by nsmith-** [comment]
But yes for some it may make sense to at least pin the major versions.

**Comment by alexander-held** [comment]
This great blog post by @henryiii provides motivation for why pinning generally is not a great idea for libraries like `coffea`: https://iscinumpy.dev/post/bound-version-constraints/.

**Comment by riga** [comment]
Sorry for posting a duplicate w.r.t. #686, I only searched in open issues (you guys are fast ^^).

Yeah, pinning the minor version might be indeed a bit too drastic. I think @nsmith- suggestion to add filters for certain versions should be fine.

Thanks for the fast responses!
