### ISSUE TITLE
awkward-numba fails unit tests

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#69]
Presumably after the large update in [awkward-array 0.9.0](https://github.com/scikit-hep/awkward-array/releases/tag/0.9.0)

**Comment by lgray** [comment]
Since awkward.numba doesn't have tables yet we're stuck here until it's implemented.

**Comment by lgray** [comment]
For right now we test awkward numba in the older versions of awkward / uproot(-methods).
At the very least we make sure it continues to work properly there.

Until Jim makes gets awkward.Table into the new awkward numba we can't really use it.

**Comment by nsmith-** [comment]
This issue goes away with awkward1 where we'll have to rework numba functions anyway.
