### ISSUE TITLE
Order of categorical bins changes in hist.identifiers

### ISSUE THREAD

**Issue by a-kapoor** [scikit-hep/coffea#694]
**Describe the bug**
In a coffea.hist with a categorical axes, the order of bins changes in hist.identifiers

**To Reproduce**
```
import numpy as np
from coffea import hist
h=hist.Hist(axes=[hist.Cat("selection", "selection"),
                  hist.Bin("x", "x", 5, -0.5, 4.5)],
            label="Cutflow")

h.fill(selection="First",x=0*np.ones(4))
h.fill(selection="Second",x=2*np.ones(3))
h.fill(selection="Third",x=3*np.ones(2))
h.fill(selection="Fourth",x=4*np.ones(2))

hs=h.project('selection')
print(hs.identifiers("selection"))
```

**Expected behavior**
It was expected that `print(hs.identifiers("selection"))` would keep the order the same as it was filled.

**Output**
`print(hs.identifiers("selection"))` gave:
[<StringBin (First) instance at 0x7fd950757cd0>, <StringBin (Fourth) instance at 0x7fd9505d9dd0>, <StringBin (Second) instance at 0x7fd950bcc810>, <StringBin (Third) instance at 0x7fd9505d9d10>]
`

**Desktop (please complete the following information):**
 Ubuntu, `coffea = 0.7.16`, `hist = 2.5.1`, `numpy = 1.21.6`

**Additional context**
Since hist.identifiers is used downstream in several places, projecting and plotting histograms with categorical axes is messed up

Something interesting I noticed (in my example case), is if the names of the categorical axes are alphabetical, example:
```
h.fill(selection="A_First",x=0*np.ones(4))
h.fill(selection="B_Second",x=2*np.ones(3))
h.fill(selection="C_Third",x=3*np.ones(2))
h.fill(selection="D_Fourth",x=4*np.ones(2))
```
,then order in `print(hs.identifiers("selection"))` remains the same as it was filled.

**Comment by lgray** [comment]
Have you tried this using the histogram package here https://github.com/scikit-hep/hist?

**Comment by a-kapoor** [comment]
> Have you tried this using the histogram package here https://github.com/scikit-hep/hist?

Hi @lgray Lindsey 
Yes, for hist it works fine.
I think the issue in Coffea hist is here:
https://github.com/CoffeaTeam/coffea/blob/b14672ef969fa0ee0e4ad150936bc6465dbde7bd/coffea/hist/hist_tools.py#L322
,where the sorting by default was expected to be "placement", it actually is "identifier"
If I set this to be placement in my code[1], even coffea.hist works fine

[1] 
```
h=hist.Hist(axes=[hist.Cat("selection", "selection" ,sorting="placement"),
                  hist.Bin("x", "x", 5, -0.5, 4.5)],
            label="Cutflow")
```

**Comment by lgray** [comment]
coffea hist is deprecated and removed now. Will not fix.
