### ISSUE TITLE
hist.copy() does not create new axis labels in memory (coffea.0.7.13)

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#697]
When I modify the x axis label of a copy of a histogram it also modifies the label on the original histogram

```
>>> import coffea.hist as hist
>>> histo = hist.Hist("Counts",
...                   hist.Cat("sample", "sample name"),
...                   hist.Bin("x", "x value", 20, -10, 10),
...                   hist.Bin("y", "y value", 20, -10, 10),
...                   hist.Bin("z", "z value", 20, -10, 10),
...                  )
>>> histo_copy = histo.copy()
>>> histo_copy.axis('x').label = 'other x'
>>> histo.axis('x').label
'other x'
```

**Comment by patrickbryant** [comment]
workaround is to use deepcopy

**Comment by andrzejnovak** [comment]
In case it wasn't mentioned yet, you should use https://github.com/scikit-hep/hist, `coffea.hist` is being deprecated, but the same behaviour iirc.

**Comment by patrickbryant** [comment]
I have been using the LCG environments to play with coffea on LPC and it does not have the Hist package:
```
>>> from Hist import hist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Hist'
```
I've requested it be added on Jira: https://sft.its.cern.ch/jira/browse/SPI-2165

**Comment by lgray** [comment]
Highly recommend using the singularity images if you are able, they are kept more up-to-date on a variety of axes.

**Comment by NJManganelli** [comment]
I think that should be...

```
from hist import Hist
#or...
import hist
```

This works fine on lxplus in LCG_102rc1 (i.e. /cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/setup.sh):
```
>>> import uproot, coffea, hist
uproot.__version__, uproot.__file__
('4.2.0', '/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/uproot/__init__.py')
>>> coffea.__version__, coffea.__file__
('0.7.13', '/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/__init__.py')
>>> hist.__version__, hist.__file__
('2.5.1', '/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/hist/__init__.py')
>>> from hist import Hist
>>> h = Hist.new.Regular(20, 0, 10).Double()
>>> h
Hist(Regular(20, 0, 10, label='Axis 0'), storage=Double())
```

**Comment by patrickbryant** [comment]
Ah yes, case sensitivity strikes again. Indeed LCG_102 now has what I need.

**Comment by patrickbryant** [comment]
It would be useful to update the documentation to point new users like myself away from coffea hist and towards scikit-hep hist. https://coffeateam.github.io/coffea/notebooks/histograms.html
