### ISSUE TITLE
Reduce memory usage of function results

### ISSUE THREAD

**Issue by btovar** [scikit-hep/coffea#699]
**Is your feature request related to a problem? Please describe.**

When using compression, functions are wrapped with:

```
# compression
return lz4f.compress(
            pickle.dumps(item, protocol=_PICKLE_PROTOCOL), compression_level=compression
        )

# decompression
return pickle.loads(lz4f.decompress(item))
```

This works well for small results, but may cause excessive memory usage for results that are larger than 1GB.  The memory used consists of:
- the actual result item
- its pickled representation
- the pickled representation compressed

In one of our runs, the pickled representation compressed is around 3GB, which means than a lower bound of extra memory is 6GB (more because the pickle representation is larger than the compressed one).  The final accumulation result of this run needed a peak of 21GB to be expanded

**Describe the solution you'd like**

We would like the final memory usage to be as close as possible to the minimum required by the result. 

**Describe alternatives you've considered**

The first alternative that we tried was to decouple the calls to something like:

```
item_pickled = lz4f.decompress(item_compressed)
del item_compressed
item = pickle.loads(item_pickled)
del item_pickled  # with no effect really, as we are about to return anyway
return item
```

Such scheme turn our max memory consumption from 21GB to about 18GB.

Further, since we are working with the WorkQueue executor that transmits data from functions at remote workers via files, we were able to compress/decompress and read/write directly the pickled output as:

```
# compress
with lz4f.open(filename, 'wb', compression_level=compression) as rf:
   return pickle.dump(item, rf, protocol=_PICKLE_PROTOCOL)

# decompress
with lz4f.open(filename, 'rb') as rf:
   return pickle.load(rf)
```

With such scheme, the memory consumption went down to 12GB for the final accumulation task. With a specialization on the dict_accumulator, we tried to pickle each of the values in the dictionary one at a time, but this did not change the memory consumption by much (around 11.5GB), so probably `pickle.load` knows to interpret each value by itself and does not need to load the whole file into memory before unpickling.

Where do you think changes like this should be incorporated in coffea?  Currently the _compression_wrapper and related utility functions are part of the` processor.executor` module, but perhaps they can be methods an executor can specialize? In our current prototype we simply override the _compression_wrapper in the WorkQueueExecutor.

I also had the idea that an accumulator and function results may define how to be serialized, say, using JSON rather than pickle. However, I don't have a use case that justifies the larger surgery. (E.g., in our case, specializing the serialization of the dict_accumulator did not buy us much.)  Any python class may define things like `_getstate_` and `_setstate_`, so maybe this is not a huge deal.

At least decoupling the calls to decompress(unpickle(item)) may be a change that benefits all executors.

**Comment by nsmith-** [comment]
I think the decoupling of the compress+pickle to remove the intermediate variable early would be a great PR!
Do you think the memory savings for direct file dump could be recreated for byte strings by using a `BytesIO` object? Essentially it gives the compressor an opportunity to do streaming compression, reducing the temporary data further.
As for more elaborate plans, I'm not sure if it makes sense to provide a specialization for serialization where pickle already defines a protocol `__getstate__`/`__setstate__` for specializing the serialization.

**Comment by btovar** [comment]
Nick, it seems that it is possible to write the compressed pickled stream to a BytesIO buffer. Let me do some tests and then prepare a pr.
