### ISSUE TITLE
Processor runners do not support schema versions

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#704]
A schema can also be versioned, as is the case for example with NanoAODSchema:
https://github.com/CoffeaTeam/coffea/blob/98a86eb6f5179bc53a17196cf7a869fc7b6ecc22/coffea/nanoevents/schemas/nanoaod.py#L153-L160
but `Runner._work_function` expects a subclass of `BaseSchema`. I would propose to relax that to `Callable` with the one argument being a base form (i.e. json-like)

e.g.
```python
run = processor.Runner(
    executor=processor.IterativeExecutor(compression=None),
    schema=processor.NanoAODSchema.v7,
)
```

Alternatively, we could change how schema versioning is done by making subclasses of `NanoAODSchema` with explicit version names (this might make it less weird)

**Comment by lgray** [comment]
Closing as no longer relevant.
