### ISSUE TITLE
Memory increasing when doing operation of nearest operation on Union 

### ISSUE THREAD

**Issue by Ming-Yan** [scikit-hep/coffea#709]
The required files could be find [here](https://github.com/Ming-Yan/coffea_nearest_memory/tree/master)

`python runner.py` to run the task, would print out the memory usage with `psutil` to monitor memory usage of the python process

We observe the memory increase from  250MB->2GB after using the nearest function applied on events.Jet and Union object (`ll_cand`)

The Union object is construct by the combinations of electron and muon arrays [[1](https://github.com/Ming-Yan/coffea_nearest_memory/blob/master/test_processor.py#L191-L222)]

```python
### Case 1: Union v.s. events.Jet -> memory increase a lot
topjet1cut=ll_cand[:,0].lep1.nearest(events.Jet)
topjet2cut=ll_cand[:,0].lep2.nearest(events.Jet)
```
and now I use the alternative way to get the nearest object , the memory usage stay with ~250MB
```python 
topjet1cut = events.Jet[ak.argsort(events.Jet.delta_r(ll_cand[:,0].lep1), axis=1)]
topjet1cut=topjet1cut[:,0]
topjet2cut = events.Jet[ak.argsort(events.Jet.delta_r(ll_cand[:,0].lep2), axis=1)]
topjet2cut=topjet2cut[:,0]
```
Trace back to the nearest function, I find the memory increase significantly at `ak.unzip` inside the `metric_table`.[[2](https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/methods/vector.py#L693)]

Is this expected in awkward array operation? @jpivarski

The memory changes significantly in 2 conditions: 
1. If loading the `CorrectedJetsFactory` in `events.Jet`:  

Test with data root file, memory increase from 250->360MB with `nearest operation)

2. `Union` is used to running the `nearest` operation: 
Testing `nearest` with both objects are `events.Jet`, memory increase from 250->360MB
```python 
### Case 2 : both are events.Jet
other = events_jet[:,0].nearest(events.Jet)
```

software versions:
`coffea=0.7.14`
`awkward=1.8.0`

**Comment by lgray** [comment]
This should be re-established in coffea 2023 or a more recent version of coffea 0.7

**Comment by Ming-Yan** [comment]
Thanks! was reolved with newer coffea version !
