### ISSUE TITLE
Python 3.6 removal

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#722]
We should stop testing and releasing coffea for python 3.6 soon, as it was end-of-life since Dec 2021: https://devguide.python.org/versions/
Some dependencies are not getting python 3.6 releases anymore:
- hist (v2.4 is last): see #720 
- awkward (v1.9.0 is last): see https://github.com/scikit-hep/awkward/issues/1626

**Comment by lgray** [comment]
Obviated by move to dask_awkward.
