### ISSUE TITLE
chunksize is ignored when using dask_executor with run_uproot_job

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#726]
Using the example here: https://github.com/CoffeaTeam/lpcjobqueue/blob/main/simple_example.py
Add the line
```
    hists, metrics = processor.run_uproot_job(
        "fileset.json",
        treename="Events",
        processor_instance=proc,
        executor=processor.dask_executor,
        executor_args=exe_args,
        # remove this to run on the whole fileset:
+       chunksize=100,
-       maxchunks=10,
+       maxchunks=1, 
    )

```

The number of events will be much more than 100 because the default chunk size is used. 

I ran the first two files from fileset.json in each dataset and got:
```
Output: {'sumw': defaultdict_accumulator(<class 'float'>, {'DoubleMuon2018A': 277497.0, 'ZJets2018': 1000.0}), 'mass': <Hist (dataset,mass) instance at 0x7f76142329d0>}
Metrics: {'bytesread': 9095433, 'columns': ['Muon_phi', 'Muon_eta', 'Muon_charge', 'Muon_mass', 'Muon_pt', 'nMuon'], 'entries': 278497, 'processtime': 4.596390008926392, 'chunks': 2}
```

**Comment by lgray** [comment]
@patrickbryant try setting `align_clusters` to false. Align clusters will override expected chunking behavior in some cases. Perhaps there is an edge we didn't anticipate.

**Comment by patrickbryant** [comment]
Ok yeah that fixes it

**Comment by nsmith-** [comment]
We should probably add a warning when `align_clusters` makes the requested chunksize not attainable (by some margin)

**Comment by lgray** [comment]
We'll fix this up (the warning) in coffea 2023.

With the changes coming to uproot.dask align_clusters / etc. becomes much more on the side of the user or some basic function we provide.

**Comment by lgray** [comment]
This is fixed now in latest uproot, there are extra creature comforts in #882 to implement max chunks and such on the pre-processed filesets.
