### ISSUE TITLE
KeyError: 'jersf' introduced for non-JER correction files named with "SF_" due to hardcoded bugfix 

### ISSUE THREAD

**Issue by demuller** [scikit-hep/coffea#727]
The hardcoded bugfix introduced for `coffea/lookup_tools/extractor.py` in [this PR](https://github.com/CoffeaTeam/coffea/commit/1d30ab21fdafc7cb07755abeab47a5a747ba2225), in particular, this snippet
```python
            if '_SF_' in thefile:
                thetype = 'jersf'
```
throws a key error when using the extractor with non-JER files that contain "SF_" in their name, in our case the muon SF root files. I have no minimal example at hand, but the error appears in the scope of the [BTVNanoCommissioning framework](https://github.com/cms-btv-pog/BTVNanoCommissioning), where we obtain the following error when running our workflows:
```bash
  File "/opt/conda/lib/python3.8/site-packages/coffea/processor/executor.py", line 1635, in _work_function
    out = processor_instance.process(events)
  File "/srv/src/BTVNanoCommissioning/workflows/ttdilep_valid_sf.py", line 331, in process
    muSFs(
  File "/srv/src/BTVNanoCommissioning/utils/correction.py", line 144, in muSFs
    ext.add_weight_sets(
  File "/opt/conda/lib/python3.8/site-packages/coffea/lookup_tools/extractor.py", line 111, in add_weight_sets
    weights, thetype = self.extract_from_file(thefile, name)
  File "/opt/conda/lib/python3.8/site-packages/coffea/lookup_tools/extractor.py", line 133, in extract_from_file
    self.import_file(thefile)
  File "/opt/conda/lib/python3.8/site-packages/coffea/lookup_tools/extractor.py", line 129, in import_file
    self._filecache[thefile] = file_converters[theformat][thetype](thefile)
KeyError: 'jersf'
```
This behavior can be fixed from our side by renaming all correction files, such that they do not contain "SF_" in their names, but I think a safer solution than the hardcoded bug fixes is needed in coffea for dealing with the jer SFs.

**Comment by lgray** [comment]
Should be fixed in #728 - oversights in a previous contribution. New coffea release on Friday. :-)

**Comment by demuller** [comment]
Many thanks for your quick fix, looking forward to the new coffea version :)

**Comment by lgray** [comment]
Yeah having to adopt more file suffixes is an annoying position to be in (because of our over subscription of base formats), and trying to parse metadata out of file names is super inconsistent. Narrowing the use of that particular override to specifically JetMET should smooth things over.
