### ISSUE TITLE
Upperbound pin on `numpy` unncessary?

### ISSUE THREAD

**Issue by jmduarte** [scikit-hep/coffea#741]
It appears `numba` 0.56 and 0.55.2 now support `numpy` 1.22. Can this upper bound pin be removed?

https://github.com/CoffeaTeam/coffea/blob/52e102fce21a3e19f8c079adc649dfdd27c92075/setup.py#L68

See: https://github.com/numba/numba/issues/8025

**Comment by lgray** [comment]
This is related to supporting python 3.6 or not. It would be a little odd to drop python 3.6 on a minor version.
I can see if I can specify different version requirements in different versions of python.

For the awkward 2 transition we've already moved on.

**Comment by lgray** [comment]
It'll be unpinned in the release later this week.
