### ISSUE TITLE
Add sphinx-copybutton support to the docs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/coffea#744]
**Is your feature request related to a problem? Please describe.**

When browsing the docs, especially the [Coffea by Example](https://coffeateam.github.io/coffea/examples.html) section, it would be nice to be able to copy the code examples with a button click. This is possible with [`sphinx-copybutton`](https://sphinx-copybutton.readthedocs.io/).

![Screenshot from 2022-11-03 11-23-47](https://user-images.githubusercontent.com/5142394/199777071-9db4b0d2-1cad-4d58-b63e-dabdae6f970e.png)

(screen shot isn't perfect there at seeing the button, but if you check the other links you can see it)

Is this of interest? If so I have support added on my fork and I can PR.

**Describe the solution you'd like**
Adopt `sphinx-copybutton` as a Sphinx extension and a component of the `dev` extra.

**Describe alternatives you've considered**

Not implementing copy on click support.

**Additional context**

c.f. https://github.com/scikit-hep/pyhf/pull/721, https://github.com/scikit-hep/pyhf/pull/1617 for examples of adding support and https://pyhf.readthedocs.io/ for an example of docs using `sphinx-copybutton`.

**Comment by matthewfeickert** [comment]
Ping @lgray @nsmith-

**Comment by nsmith-** [comment]
I think it sounds great!

**Comment by lgray** [comment]
Agreed, looks nice :-)
