### ISSUE TITLE
entry_start and entry_stop ignored in NanoEventsFactory.from_root if permit_dask=True

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#807]
**Describe the bug**
entry_start and entry_stop ignored in NanoEventsFactory.from_root if permit_dask=True.
I'm observing this by noticing file reading takes really long even though the number of requested entries is rather small and also by setting `UprootSourceMapping._debug = True`

I see that the Runner dropped using these parameters and switched to a simple slice instead. Right now there seems to be no way to only load to avoid always loading all rows. This makes debugging extremely slow.

Coffea version 2023.5.0

**Comment by lgray** [comment]
That whole interface needs to be updated. I'll make sure its fixed. The runner interface as it is right now is not great, it's a release candidate for a reason. 

In particular uproot.dask does not respect start/stop and the way you control operating on subranges is by selecting a (range of) partition(s) generated from chunking up the file. Though thinking a bit more this could be put in uproot (but it's a slight duplication of existing functionality).

This isn't so much a bug as something that currently just has a bad/naive implementation.

While you are working with things right now I suggest you either make a small skim of a file you want to use or don't use the processor/runner interface until is it updated with a better implementation. You'll be able to stuff it in a processor once everything is in shape.

**Comment by lgray** [comment]
This is going to get a wontfix in coffea, since it is being dealt with in dask-awkward / maybe uproot.
I'd move this issue to either dask-awkward or uproot (I'd go with dask-awkward first!) and distill the reproducer to involve dask-awkward alone.
