### ISSUE TITLE
Follow up issues for ml_tools

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#833]
List of to-do's for #798 for after it is merged:
- [x] use empty_if_typetracer / length_one_if_typetracer to remove need user to hint necessary columns
- [x] use weakref/dask.delayed references to have fast tracing while robustly shipping large networks to processing cluster
- [x] update documentation once empty_if_typetracer / length_one_typetracer solution available
- [x] re-enable triton testing when dask_awkward can handle nested dask collections in kwargs (https://github.com/CoffeaTeam/coffea/pull/843)

@yimuchen

**Comment by nsmith-** [comment]
For the second bullet, let's try to avoid weakref whenever possible.

**Comment by lgray** [comment]
It's necessary if you want to do column_optimization locally and then also have efficient execution remotely.

We'll figure it out  - I don't like the pattern either.

**Comment by lgray** [comment]
We now have a much better way to include ml models in the task graph that seems to not incur that much serialization.
