### ISSUE TITLE
Updates are not being published to PyPI - intentional?

### ISSUE THREAD

**Issue by tomeichlersmith** [scikit-hep/coffea#845]
**Describe what you want to do**
I would like to be able to `pip install` coffea and use more recent releases, but releases since the switch to CalVer are not being published to PyPI. 
- [coffea page on PyPI](https://pypi.org/project/coffea/)

**The Issue**
The cause of this bug is a tight requirement on the format of tags that can trigger the CI.

https://github.com/CoffeaTeam/coffea/blob/cc4c3919f1e056962aa9a3f06a6f11559d3c1d6d/.github/workflows/ci.yml#L9-L10

Is this intentional? If so, I understand and I'll just need to install coffea from `git` to use more recent development versions. If it is unintentional, I believe one can resolve this issue by loosening the tag format to something like `v**`.

**Comment by lgray** [comment]
```bash
pip install coffea --pre --upgrade
```
will get you the pre-releases for coffea 2023 :-)

If you want the super-bleeding edge:
```bash
pip install git+https://github.com/CoffeaTeam/coffea.git@master
```

There should be a new pre-release coming this week.

**Comment by lgray** [comment]
Moreover, if you look at the release history you will see the published pre-releases:
https://pypi.org/project/coffea/#history
