### ISSUE TITLE
Followup issue for new features to PackedSelection 

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#848]
Things to finish later for #797 

- [ ] understand why compatible_parititions doesn't work through slices
- [ ] double check for reducing the total number of calls to `.compute()`
- [ ] ensure no unnecessary eager `len()` calls on dak.Arrays

**Comment by ikrommyd** [comment]
I would also add "do another check for unnecessary `len` calls on `dask_awkward` collections".

**Comment by lgray** [comment]
I gave it a once-over before I merged it but sure.

**Comment by ikrommyd** [comment]
@lgray In https://github.com/CoffeaTeam/coffea/pull/895, I've partially adressed the 2nd point, meaning I've reduced the number of compute calls in `PackedSelection` by 2 but there are compute calls that can be reduced in tests to make them run quicker.

I've also checked again for unnecessary eager `len()` and didn't find any. I do see a couple in Weights but I don't know if those are supposed to only hit eager arrays. If those are fine you can mark the 3rd point as done.

I'm planning to fully address the first 2 points in a separate PR. If tests are good, I'm fine with merging https://github.com/CoffeaTeam/coffea/pull/895

**Comment by lgray** [comment]
We may wanna think about that a bit more. I'm still somewhat against calling computes for people unless it's really necessary, it introduce unexpected slowness.

Is there any way we can reorganize things to return futures to the user for them to compute?

**Comment by ikrommyd** [comment]
The only computes are while saving arrays (where the user has the option to call compute later) and while printing statistics of the cutflow and N-1 selections. I guess we can also add the option to print later, or warn that this will compute the arrays on the spot. For saving, I just made the default to be `compute=False`.

**Comment by lgray** [comment]
I think this is done now. Reopen if not.
