### ISSUE TITLE
possibly make preprocessing step more lazy

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/coffea#85]
I was playing around with these tools and some local NanoAOD based on the example notebook with a `DimuonProcessor` and `processor.run_uproot_job`. The preprocessing step was taking a while since I have a large number of files and I only wanted to test one or two chunks, so I made a couple of additions in https://github.com/aminnj/fnal-column-analysis-tools/commit/61108df7fa72b12ca538ebda307200d9ce56a70d , including a `maxchunks` parameter which limits the number of chunks per dataset.

Currently the event chunking loops through files and calls `uproot.numentries`. I made it multi-threaded since it takes an executor. And if `maxchunks` is specified, making the chunking lazy saves a lot of time. I didn't tune the magic numbers too hard, though for single digit file counts, the threadpool overhead wasn't worth it.

Is there another feature I missed, or can this be done in a better way?

**Comment by nsmith-** [comment]
The usage of a threadpool for `numentries` is a really good idea.
For lazy chunking, it looks good, I suppose this is restricted to when the user wants to test a small number of files initially?
Feel free to PR and we can continue to discuss there.

**Comment by aminnj** [comment]
Yes, mainly for small scale tests.
PR here: https://github.com/CoffeaTeam/fnal-column-analysis-tools/pull/86

**Comment by nsmith-** [comment]
Fixed in #86
