### ISSUE TITLE
Add "autodiff" issue label

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/coffea#899]
(Just a suggestion!)

Since autodiff issues tend to be cross-package, it would be nice to have common issue labels for them. This is what we're using in Awkward and Vector: "`autodiff`", "Issue related to auto-differentiation", color `#268214`.

What other HEP packages can be involved in autodiff, @alexander-held, @lukasheinrich, ...?

Cc: @Saransh-cpp, who will be working on cross-cutting issues in autodiff next year.

**Comment by alexander-held** [comment]
This is a nice initiative, thanks for starting it! For other packages: I'm sure we'll run into more of them as the project evolves, for now I think awkward / coffea / vector probably cover the core.
