### ISSUE TITLE
Different interfaces for hist.rebin() and hist.group()

### ISSUE THREAD

**Issue by kpedro88** [scikit-hep/coffea#90]
```
Signature: hfcat.rebin(old_axis, new_axis)
```
vs.
```
Signature: hfcat.group(new_axis, old_axes, mapping, overflow='none')
```

Since these are conceptually similar operations, ideally the order of arguments would be the same (old_axis, new_axis, ...).

**Comment by nsmith-** [comment]
100% agree, I was trying to pay attention to things like this but missed it.  I'll see how much code it breaks before implementing, although as we're in pre-v1.0 I could in principle change it.

**Comment by andrzejnovak** [comment]
If this is revisited, could we also have an alternative syntax, where the axis would be created implicitly by just specifying the new binning?
