### ISSUE TITLE
What is the release model of coffea ?

### ISSUE THREAD

**Issue by GaetanLepage** [scikit-hep/coffea#904]
I see that there are two kinds of releases: `202x.y.z.rcX` and `0.x.y` (ex: `0.7.22`).
Which one is supposed to be used by a regular user ?

**Comment by lgray** [comment]
rc denotes release candidate - not yet production grade / next generation.

The latest non-candidate releases are all 0.7.x.
Once coffea 2023 and the switch to dask is fully settled there will be a 202x.y.z release without the `rc` postfix.

You may try the release candidates if you like, but understand they are works in progress.

**Comment by GaetanLepage** [comment]
Ok ! Thank you for this answer :)
