### ISSUE TITLE
Failed to run a notebook example

### ISSUE THREAD

**Issue by grasph** [scikit-hep/coffea#907]
**Describe the bug**

While trying to run the examples using binder I get the following error:

 `from partially initialized module 'coffea' (most likely due to a circular import) (/home/jovyan/binder/coffea/__init__.py) ` 

I've tried with [nanoevents.ipynb](https://github.com/CoffeaTeam/coffea/blob/master/binder/nanoevents.ipynb) and [processor.ipynb](https://github.com/CoffeaTeam/coffea/blob/master/binder/processor.ipynb).

**To Reproduce**

Click on https://mybinder.org/v2/gh/coffeateam/coffea/master?filepath=binder%2Fprocessor.ipynb and execute the first cell that contains code.

**Comment by lgray** [comment]
Thanks @grasph! Someone will look into it in the coming week. Is this with coffea 2023 or coffea 0.7?

**Comment by lgray** [comment]
If you're taking the present master of coffea to make your binder that might be it - things are in a moderate state of flux. 
You may want to try starting a binder from a non 2023 full release like https://github.com/CoffeaTeam/coffea/tree/v0.7.22 (click and then launch binder from this tag rather than master!)

We'll fix the problem running in master though, for sure.

**Comment by grasph** [comment]
Hello Lindsey,

Thanks for your prompt action. The binder links (badge and links in the notebook) always launch from the master branch. We can select the branch by starting from the binder page, but it was taking too long (stuck on pushing the image) when I tried.

I've solve my issue by  cloning the repository and running the notebook on my computer. It's fine for me to close the issue.

Philippe.

**Comment by lgray** [comment]
Ah yeah - binderhub itself can sometimes take a bit because we stick xrootd in the image and it brings some dependencies. The image *does* finish building, and if you try the binder link again later it should boot up promptly since there's a cache.
