### ISSUE TITLE
Possible Bug in factory.py

### ISSUE THREAD

**Issue by alikaanguven** [scikit-hep/coffea#918]
Hi. I am new to Coffea, but I think I found an unexpected behaviour with the version '2023.10.0rc1'.
While using a previous version '0.7.21' I was able to open a NanoAOD with the NanoEventsFactory.from_root()
method, but now something is not right.

Could you tell me if this is an expected behaviour?
I tried to check the discussions, and issues sections, but unfortunately could not find a solution.

**To Reproduce**
```python
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

fname = "/<path_to_dir>/dataFromFelix-NanoAODv9.root"
events = NanoEventsFactory.from_root(
    fname,
    schemaclass=NanoAODSchema,
    metadata={"Soft Displaced Vertices": "Our first attempt"},
).events()
```

**Output**
```python
File ~/.conda/envs/coffea_env2/lib/python3.11/site-packages/coffea/nanoevents/factory.py:372, in NanoEventsFactory.from_root(cls, file, treepath, entry_start, entry_stop, chunks_per_file, runtime_cache, persistent_cache, schemaclass, metadata, uproot_options, access_log, iteritems_options, use_ak_forth, permit_dask)
    370     entry_start = 0
    371 if entry_stop is None or entry_stop > tree.num_entries:
--> 372     entry_stop = tree.num_entries
    374 partition_key = (
    375     str(tree.file.uuid),
    376     tree.object_path,
    377     f"{entry_start}-{entry_stop}",
    378 )
    379 uuidpfn = {partition_key[0]: tree.file.file_path}

AttributeError: 'ReadOnlyDirectory' object has no attribute 'num_entries'
```

**Debug Output**
```python
%debug
> /<path_to_conda_env>/lib/python3.11/site-packages/coffea/nanoevents/factory.py(372)from_root()
    370             entry_start = 0
    371         if entry_stop is None or entry_stop > tree.num_entries:
--> 372             entry_stop = tree.num_entries
    373 
    374         partition_key = (

ipdb>  type(file)
<class 'str'>
ipdb>  type(tree)
<class 'uproot.reading.ReadOnlyDirectory'>
ipdb>  tree
<ReadOnlyDirectory '/' at 0x7fe82c1ce1d0>
ipdb>  tree['Events']
<TTree 'Events' (1699 branches) at 0x7fe82c635650>
```

**Desktop**
 - OS: "CentOS Linux 7 (Core)"
 - Python Version: "3.11.6"
 - Coffea Version: "2023.10.0rc1"
 - UprootVersion: "5.1.2"

**Comment by alikaanguven** [comment]
Actually, inspecting now a bit more I really think that:

[Line 367 in factor.py](https://github.com/CoffeaTeam/coffea/blob/5f7651aff69cf4fb19e5c7cbcb18be5fe9c89a91/src/coffea/nanoevents/factory.py#L367C13-L367C17) should be replaced with:

```python
tree = uproot.open(file, **uproot_options)[treepath]
```

**Comment by lgray** [comment]
This is documentation that needs to change.

You should specify fname as is allowed by via uproot:
https://github.com/scikit-hep/uproot5/blob/main/src/uproot/_dask.py#L109-L132

i.e.: `fname = "/<path_to_dir>/dataFromFelix-NanoAODv9.root:Events"` would be acceptable as would `fname = {"/<path_to_dir>/dataFromFelix-NanoAODv9.root": "Events"}`

We'll update the documentation to deal with this correctly, but the unification with the underlying uproot interface is in general a good thing.
