### ISSUE TITLE
`.metric_table()` and `.nearest()` don't work in certain cases for delayed nanoevents when `return_combinations` and `return_metric` are set to `True` respectively

### ISSUE THREAD

**Issue by ikrommyd** [scikit-hep/coffea#924]
**Describe the bug**
This issue is just for tracking since @lgray said it's almost certainly the fact that "the behavior catching for dask awkward only assumes one output."
The methods `.metric_table()` and `.nearest()` don't work in delayed nanoevents when `return_combinations` and `return_metric` are set to `True` respectively and fail with `TypeError: meta must be an instance of an Awkward Array, not <class 'tuple'>.`

**To Reproduce**
```python
from coffea.nanoevents import NanoEventsFactory

eagerevents = NanoEventsFactory.from_root(
    {
        "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"
    },
    delayed=False,
).events()

daskevents = NanoEventsFactory.from_root(
    {
        "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"
    },
    delayed=True,
).events()

print(eagerevents.Electron.metric_table(eagerevents.TrigObj, return_combinations=True))
print(eagerevents.Electron.nearest(eagerevents.TrigObj, return_metric=True))

print(daskevents.Electron.metric_table(daskevents.TrigObj, return_combinations=True))
print(daskevents.Electron.nearest(daskevents.TrigObj, return_metric=True))
```

The first two print statements work as expected.
The other two fail with `TypeError: meta must be an instance of an Awkward Array, not <class 'tuple'>.`

**Expected behavior**
They should all work.

**Comment by ikrommyd** [comment]
@lgray please dm me on slack when you get the chance like you said in the awkward-dask meeting

**Comment by ikrommyd** [comment]
This is partially fixed by https://github.com/CoffeaTeam/coffea/pull/925 but only works with dask_awkward column optimization off. Waiting for upstream dask_awkward fixes to completely close this one.

**Comment by lgray** [comment]
Fixed by https://github.com/dask-contrib/dask-awkward/pull/430
