### ISSUE TITLE
LumiList is broken

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#931]
**Describe the bug**
LumiList cannot be used in processor outputs.

**To Reproduce**
```
>>> from coffea.processor import accumulate
>>> from coffea.lumi_tools import LumiList
>>> accumulate([LumiList() for _ in range(3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/coffea/processor/accumulator.py", line 112, in accumulate
    accum = add(accum, next(gen))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coffea/processor/accumulator.py", line 70, in add
    raise ValueError(
ValueError: Cannot add accumulators of incompatible type (<class 'coffea.lumi_tools.lumi_tools.LumiList'> vs. <class 'coffea.lumi_tools.lumi_tools.LumiList'>)
```
this breaks the ability to return a `LumiList` from a processor output. Looking at the history, I don't think this ever worked, but it should have!

Workaround:
```python
def LumiList_add(self, other):
    out = LumiList()
    out += other
    return out

LumiList.__add__ = LumiList_add
```

Long-term solution: this class needs to be made dask-friendly.

**Comment by lgray** [comment]
Can't we just return `events.run, events.luminosityBlock` as arrays and then process that locally?

Or do we want it to be part of the dask workflow?

**Comment by lgray** [comment]
@nsmith- best way forward, in your opinion?

**Comment by nsmith-** [comment]
Now that the processor "sees" the whole dataset at once, I would think this can be replaced with https://docs.dask.org/en/latest/generated/dask.array.unique.html but the `axis` argument is unsupported. Further, even if we pack the two integers into one array to get around the issue, the `unique` method only accepts arrays with known lengths.

The basic requirement here is we have two dask-awkward arrays of type `? * uint32`, and we would like to find unique pairs in these lists.

**Comment by lgray** [comment]
That's interesting because dask-awkward arrays that have been constructed from a `preprocess`ed list of root files will have known lengths (because the step/chunk boundaries will be supplied), and when calculating lumi you shouldn't take the events/runs lists from an `events` object after analysis cuts (which would indeed create unknown lengths again in certain cases).

People will be using `preprocess` for analyses mature enough to want to calculate lumi, so maybe we can use `da.unique`?

**Comment by nsmith-** [comment]
Actually, nevermind. I guess it does work:
```python
from coffea.nanoevents import NanoEventsFactory
import dask.array as da
import dask_awkward as dak
import dask

events = NanoEventsFactory.from_root(
    {"tests/samples/nano_dimuon.root": "Events"},
).events()

def unique(runs: dak.Array, lumis: dak.Array):
    merged = (
        (runs.to_dask_array().astype("u8") << 32)
        | lumis.to_dask_array().astype("u8")
    )
    uniques = da.unique(merged)
    return (uniques >> 32), (uniques & 0xffffffff)


dask.compute(unique(events.run, events.luminosityBlock))
```

returns
```
((array([315267], dtype=uint64), array([205], dtype=uint64)),)
```

**Comment by lgray** [comment]
I guess we can add in the packing thing as a convenience function in coffea or make LumiList do that when it gets a dask collection.

Make a PR. :-)

**Comment by lgray** [comment]
On second thought - this causes some pre-mature optimization that can cost quite some time when building task graphs.

It shouldn't be that hard to make a layer that does what we want with raw awkward arrays;`np.unique(<an-awkward-array>)` works after all.

**Comment by nsmith-** [comment]
I thought `da.unique` didn't work on dask-awkward arrays? Or what do you mean by premature optimization?

**Comment by lgray** [comment]
It only doesn't work on typetracers and it's easy to get around that.

**Comment by lgray** [comment]
The "pre-mature" optimization is pondering when we should do the `np.unique` and corresponding tree reduce.
