### ISSUE TITLE
iterative_executor crashes

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/coffea#96]
I think because of https://github.com/CoffeaTeam/coffea/blob/1b0b8fac4ce0d774e4c8785a2c43188b95c12667/coffea/processor/executor.py#L116 
and
https://github.com/CoffeaTeam/coffea/blob/1b0b8fac4ce0d774e4c8785a2c43188b95c12667/coffea/processor/executor.py#L130,
https://github.com/CoffeaTeam/coffea/blob/1b0b8fac4ce0d774e4c8785a2c43188b95c12667/coffea/processor/executor.py#L30 will fail. Adding `workers=1` to the argument list of `iterative_executor` fixes it for me

**Comment by nsmith-** [comment]
ack yes, anyway `workers` in the context of futures executor can and should be different from the number of parallel threads used to preprocess the files (and compute the chunking)

**Comment by lgray** [comment]
I'll supply a PR and some tests in 1 or 2 hours, unless you wanna do it @nsmith-.

**Comment by nsmith-** [comment]
Sounds like you're on it, thanks!

**Comment by lgray** [comment]
@aminnj Fixed in #99 and v0.5.1 of coffea.
