### ISSUE TITLE
make progress of futures based on callbacks

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/coffea#97]
Would there be opposition to changing
https://github.com/CoffeaTeam/coffea/blob/1b0b8fac4ce0d774e4c8785a2c43188b95c12667/coffea/processor/executor.py#L43-L51
into
```python
for job in tqdm(concurrent.futures.as_completed(futures),disable=not status, unit=unit, total=len(futures)):
    accumulator += job.result()
```
which relies on callbacks instead of polling every 1s (I guess this saves 1/2 sec on average). Also, `as_completed` can take a timeout parameter.

If you think it's useful, I can make a small PR later today.

**Comment by lgray** [comment]
@aminnj yeah I use as_completed for spark and parsl. It would be nice to uniformize the code a bit. 

If you wanna give it a go, please do. If you'd rather I roll it into the PR I'll take care of for #96, once I'm off this bus, that's fine too.

**Comment by aminnj** [comment]
Turned out it only took a couple mins so I put in a PR (I thought I had screwed up my setup earlier because of the repo name change :) ). If you want to lump it with the other change, go ahead.

**Comment by lgray** [comment]
Sure, I'll grab the commit from your PR in a bit.

Thanks!

**Comment by nsmith-** [comment]
Please don't, there's a good reason not to use as_completed.  It queues up the incoming results *in the order of execution* so if one job stalls and the others continue, the queue will fill up with results.  If the result package is large the driver will run out of memory.  I originally used as_completed but moved away from it due to running into this problem.

**Comment by nsmith-** [comment]
That being said, I would prefer a callback but unless one exists that doesn't guarantee the order of results matches the order of executor submission, I would highly advise against it.

**Comment by lgray** [comment]
Thanks for the heads up. Will leave as is. I'll try out what you're doing with spark / parsl.

**Comment by aminnj** [comment]
Sorry I'm a bit confused. I thought the iterator returns futures for things that complete first without regard to the order in which they were `executor.submit`ted based on
```python
import concurrent.futures
import time
import random

def work(i):
    time.sleep(random.random())
    return i

executor = concurrent.futures.ProcessPoolExecutor(4)
futures = [executor.submit(work,i) for i in range(20)]
for future in concurrent.futures.as_completed(futures):
    print future.result()
```
so that if one future takes forever, the others will have been aggregated by the time that one finishes

**Comment by nsmith-** [comment]
Hmm that's pretty convincing evidence.  Maybe what I was seeing was that `as_completed` kept a reference to the future, preventing garbage collection?  All I know is that I saw linear memory growth with large processing.  Certainly there might be other causes.

**Comment by nsmith-** [comment]
Yeah, it keeps a reference for too long:
```python
import concurrent.futures
import time
import random
import os
import sys

PARENTPID = os.getpid()

class ReturnItem:
    def __init__(self, i):
        self.i = i
        self.start = time.time()

    def __str__(self):
        self.stop = time.time()
        return "Item %d, waited %f seconds in line" % (self.i, self.stop-self.start)

    def __del__(self):
        # Don't count cleanup in the child processes
        if os.getpid() == PARENTPID:
            print(f"{self.i} got cleaned up")


def work(i):
    time.sleep(random.random()*5)
    return ReturnItem(i)


executor = concurrent.futures.ProcessPoolExecutor(4)
futures = set(executor.submit(work,i) for i in range(20))

if len(sys.argv) > 1:
    for future in concurrent.futures.as_completed(futures):
        print(future.result())
else:
    while len(futures) > 0:
        finished = set(job for job in futures if job.done())
        for job in finished:
            print(job.result())
        futures -= finished
        del finished
        time.sleep(1)
```

**Comment by nsmith-** [comment]
Now, as I learned the hard way, `__del__` is not guaranteed to be called in python, but my prior experience leads me to believe this accurately represents the lifecycle of the `ReturnItem`

**Comment by lgray** [comment]
Gonna reopen this since you're chewing on it.

**Comment by nsmith-** [comment]
Ok, you can also see from the source that it keeps a reference to `fs` for the duration of the function: https://github.com/python/cpython/blob/f85af035c5cb9a981f5e3164425f27cf73231b5f/Lib/concurrent/futures/_base.py#L200

So yeah, best to avoid this.

**Comment by aminnj** [comment]
Ah, interesting. thanks, that was instructive!

**Comment by nsmith-** [comment]
Closing, as it sounds we're all in agreement now.
